import { randomUUID } from "node:crypto";
import { getRuntimeEnv } from "../../../db/runtime-env";
import { POST as createSale } from "../sales/route";

const sha256=async(value:string)=>Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value)))).map(x=>x.toString(16).padStart(2,"0")).join("");
async function credential(req:Request){const token=(req.headers.get("authorization")||"").replace(/^Bearer\s+/i,"");if(!token)return null;return getRuntimeEnv().DB.prepare("SELECT c.id,c.tenant_id tenantId,c.branch_id branchId,c.terminal_id terminalId,c.user_id userId,u.email,t.code terminalCode FROM desktop_terminal_credentials c JOIN app_users u ON u.id=c.user_id AND u.active=1 JOIN terminals t ON t.id=c.terminal_id AND t.status='active' WHERE c.token_hash=? AND c.status='active'").bind(await sha256(token)).first<{id:string;tenantId:string;branchId:string;terminalId:string;userId:string;email:string;terminalCode:string}>()}
export async function GET(req:Request){const c=await credential(req);if(!c)return Response.json({error:"Credencial de terminal inválida"},{status:401});const d=getRuntimeEnv().DB,[settings,products,customers]=await Promise.all([d.prepare("SELECT t.name company,b.name branch,s.currency,s.timezone,s.allow_negative_stock allowNegativeStock,s.receipt_format receiptFormat FROM tenants t JOIN branches b ON b.id=? LEFT JOIN business_settings s ON s.tenant_id=t.id WHERE t.id=?").bind(c.branchId,c.tenantId).first(),d.prepare("SELECT p.id,p.sku,p.barcode,p.name,p.price_minor priceMinor,p.cost_minor costMinor,p.track_inventory trackInventory,p.version,COALESCE((SELECT SUM(ib.quantity) FROM inventory_balances ib JOIN warehouses w ON w.id=ib.warehouse_id WHERE ib.product_id=p.id AND w.branch_id=?),0) stock,(SELECT GROUP_CONCAT(code,',') FROM product_barcodes x WHERE x.product_id=p.id) barcodeList FROM products p WHERE p.tenant_id=? AND p.active=1 ORDER BY p.name").bind(c.branchId,c.tenantId).all(),d.prepare("SELECT id,document_number documentNumber,name,credit_limit_minor creditLimitMinor,blocked,active FROM customers WHERE tenant_id=? AND active=1 ORDER BY name").bind(c.tenantId).all()]);await d.prepare("UPDATE desktop_terminal_credentials SET last_sync_at=CURRENT_TIMESTAMP WHERE id=?").bind(c.id).run();return Response.json({terminal:{id:c.terminalId,code:c.terminalCode,tenantId:c.tenantId,branchId:c.branchId},catalogVersion:Date.now(),settings,products:products.results.map((p)=>({...p,barcodes:String(p.barcodeList||"").split(",").filter(Boolean)})),customers:customers.results,serverTime:new Date().toISOString()})}
export async function POST(req:Request){const c=await credential(req);if(!c)return Response.json({error:"Credencial de terminal inválida"},{status:401});const body=await req.json() as {operations?:{id:string;type:"sale";payload:Record<string,unknown>}[]};if(!Array.isArray(body.operations)||body.operations.length>100)return Response.json({error:"Lote de sincronización inválido"},{status:400});const d=getRuntimeEnv().DB,results=[];
  for(const operation of body.operations){if(!operation.id||operation.type!=="sale"){results.push({id:operation.id,status:"rejected",error:"Tipo no soportado"});continue}const previous=await d.prepare("SELECT status,response,server_entity_id serverEntityId FROM desktop_sync_operations WHERE terminal_id=? AND operation_id=?").bind(c.terminalId,operation.id).first<{status:string;response:string;serverEntityId:string}>();if(previous){results.push({id:operation.id,status:previous.status,serverEntityId:previous.serverEntityId,response:previous.response?JSON.parse(previous.response):null,duplicate:true});continue}
    const payload={...operation.payload,localId:operation.id},saleReq=new Request(new URL("/api/sales",req.url),{method:"POST",headers:{"content-type":"application/json","oai-authenticated-user-email":c.email,"x-pos360-tenant-id":c.tenantId,"x-pos360-branch-id":c.branchId},body:JSON.stringify(payload)}),response=await createSale(saleReq),data=await response.json() as {sale?:{id?:string};error?:string},status=response.ok?"applied":"conflict";
    await d.batch([d.prepare("INSERT OR IGNORE INTO desktop_sync_operations(id,tenant_id,terminal_id,operation_id,entity_type,server_entity_id,status,payload,response) VALUES (?,?,?,?,?,?,?,?,?)").bind(randomUUID(),c.tenantId,c.terminalId,operation.id,"sale",data.sale?.id||null,status,JSON.stringify(payload),JSON.stringify(data)),d.prepare("INSERT INTO sync_events(id,tenant_id,node_id,event_type,entity_id,payload,status) VALUES (?,?,?,?,?,?,?)").bind(randomUUID(),c.tenantId,c.terminalId,status==="applied"?"desktop.sale.applied":"desktop.sale.conflict",data.sale?.id||operation.id,JSON.stringify(data),status),...(status==="conflict"?[d.prepare("INSERT OR IGNORE INTO sync_conflicts(id,tenant_id,entity_type,entity_id,device_id,local_version,server_version,payload,status) VALUES (?,?,?,?,?,1,1,?,'pending')").bind(randomUUID(),c.tenantId,"sale",operation.id,c.terminalId,JSON.stringify({error:data.error,payload}))]:[])]);results.push({id:operation.id,status,serverEntityId:data.sale?.id,error:data.error,response:data})
  }
  await d.prepare("UPDATE desktop_terminal_credentials SET last_sync_at=CURRENT_TIMESTAMP WHERE id=?").bind(c.id).run();return Response.json({results,serverTime:new Date().toISOString()})
}
