const $=id=>document.getElementById(id),money=n=>new Intl.NumberFormat("es-CO",{style:"currency",currency:"COP"}).format(n/100);let selected=null,cart=[];
async function refresh(){const s=await window.pos360.stats();$("stats").textContent=`Ventas locales: ${s.sales}\nPendientes: ${s.pending}\nConflictos: ${s.conflicts}\nSQLite: ${s.integrity}`}
async function find(){selected=await window.pos360.find($("scanner").value.trim());$("product").textContent=selected?`${selected.name} · ${money(selected.price_minor)} · Stock ${selected.stock}`:"Producto no encontrado"}
function draw(){$("cart").innerHTML=cart.map((x,i)=>`<div><b>${x.name}</b><input data-i="${i}" type="number" min="0.001" step="0.001" value="${x.quantity}"><span>${money(Math.round(x.price*x.quantity))}</span></div>`).join("");const total=cart.reduce((s,x)=>s+Math.round(x.price*x.quantity),0);$("total").textContent=money(total);document.querySelectorAll("#cart input").forEach(input=>input.onchange=()=>{cart[Number(input.dataset.i)].quantity=Number(input.value);draw()})}
$("scanner").onkeydown=e=>{if(e.key==="Enter")find().then(()=>{if(selected){cart.push({productId:selected.id,name:selected.name,price:selected.price_minor,quantity:1});$("scanner").value="";draw()}})};$("add").onclick=()=>find().then(()=>{if(selected){cart.push({productId:selected.id,name:selected.name,price:selected.price_minor,quantity:1});draw()}});
$("sell").onclick=async()=>{if(!cart.length)return;const total=cart.reduce((s,x)=>s+Math.round(x.price*x.quantity),0),sale=await window.pos360.sale({items:cart.map(({productId,quantity})=>({productId,quantity})),payments:[{method:$("method").value,amountMinor:total}]});alert(`Venta ${sale.operationId} guardada en SQLite`);cart=[];draw();await refresh()};
$("sync").onclick=async()=>{const result=await window.pos360.sync();$("status").textContent=result?.offline?"● Sin internet · cola protegida":"● Sincronizado";await refresh()};
$("connect").onclick=async()=>{await window.pos360.configure({baseUrl:$("url").value,token:$("token").value});const snapshot=await window.pos360.pull();$("terminal").textContent=`${snapshot.terminal.code} · ${snapshot.settings.branch}`;$("setup").close();await refresh()};
refresh().catch(()=>$("setup").showModal());
