import { randomUUID } from "node:crypto";
import { requireAccess } from "../../../db/authz";
import { getRuntimeEnv } from "../../../db/runtime-env";
import { inventoryMovement, negativeStockAllowed } from "../../../db/inventory";

export async function GET(req: Request) {
  const access=await requireAccess(req,"inventory"); if(access.error)return access.error;
  const d=getRuntimeEnv().DB,T=access.user.tenantId;
  const [warehouses,stocks,transfers,counts,lots,serials,presentations,ledger]=await Promise.all([
    d.prepare("SELECT w.id,w.name,w.code,w.active,b.name branchName,COALESCE(SUM(s.quantity),0) units,COALESCE(SUM(s.quantity*s.average_cost_minor),0)/100.0 value FROM warehouses w JOIN branches b ON b.id=w.branch_id LEFT JOIN inventory_balances s ON s.warehouse_id=w.id WHERE w.tenant_id=? GROUP BY w.id ORDER BY w.name").bind(T).all(),
    d.prepare("SELECT s.id,s.warehouse_id warehouseId,w.name warehouseName,p.id productId,p.name,p.sku,p.category,s.quantity,s.average_cost_minor averageCostMinor,s.average_cost_minor/100.0 averageCost,s.minimum_stock minimumStock,(s.quantity<=s.minimum_stock AND s.minimum_stock>0) lowStock FROM inventory_balances s JOIN warehouses w ON w.id=s.warehouse_id JOIN products p ON p.id=s.product_id WHERE s.tenant_id=? ORDER BY lowStock DESC,p.name,w.name").bind(T).all(),
    d.prepare("SELECT t.id,t.number,t.status,t.created_at createdAt,f.name fromName,x.name toName,(SELECT SUM(quantity) FROM stock_transfer_lines WHERE transfer_id=t.id) units FROM stock_transfers t JOIN warehouses f ON f.id=t.from_warehouse_id JOIN warehouses x ON x.id=t.to_warehouse_id WHERE t.tenant_id=? ORDER BY t.created_at DESC LIMIT 30").bind(T).all(),
    d.prepare("SELECT c.id,c.number,c.status,c.created_at createdAt,w.name warehouseName,COALESCE(SUM(ABS(l.difference)),0) difference FROM stock_counts c JOIN warehouses w ON w.id=c.warehouse_id LEFT JOIN stock_count_lines l ON l.count_id=c.id WHERE c.tenant_id=? GROUP BY c.id ORDER BY c.created_at DESC LIMIT 20").bind(T).all(),
    d.prepare("SELECT l.id,l.lot_number lotNumber,l.expiration_date expirationDate,l.laboratory,l.health_registration healthRegistration,l.quantity,p.name productName,w.name warehouseName,CAST(julianday(l.expiration_date)-julianday('now') AS INTEGER) daysToExpire FROM product_lots l JOIN products p ON p.id=l.product_id JOIN warehouses w ON w.id=l.warehouse_id WHERE l.tenant_id=? ORDER BY l.expiration_date").bind(T).all(),
    d.prepare("SELECT s.id,s.serial_number serialNumber,s.warranty_months warrantyMonths,s.status,p.name productName,w.name warehouseName FROM product_serials s JOIN products p ON p.id=s.product_id JOIN warehouses w ON w.id=s.warehouse_id WHERE s.tenant_id=? ORDER BY s.created_at DESC LIMIT 50").bind(T).all(),
    d.prepare("SELECT x.id,x.name,x.unit,x.conversion_factor conversionFactor,x.barcode,x.sale_price salePrice,x.active,p.name productName FROM product_presentations x JOIN products p ON p.id=x.product_id WHERE x.tenant_id=? ORDER BY p.name,x.name").bind(T).all(),
    d.prepare("SELECT l.id,l.movement_type movementType,l.quantity,l.previous_balance previousBalance,l.balance_after balanceAfter,l.average_cost_minor averageCostMinor,l.reason,l.reference,l.created_at createdAt,p.name productName,w.name warehouseName,u.display_name userName FROM inventory_ledger l JOIN products p ON p.id=l.product_id JOIN warehouses w ON w.id=l.warehouse_id JOIN app_users u ON u.id=l.user_id WHERE l.tenant_id=? ORDER BY l.created_at DESC,l.rowid DESC LIMIT 100").bind(T).all(),
  ]);
  return Response.json({warehouses:warehouses.results,stocks:stocks.results,alerts:stocks.results.filter(x=>Boolean(x.lowStock)),transfers:transfers.results,counts:counts.results,lots:lots.results,serials:serials.results,presentations:presentations.results,ledger:ledger.results});
}

type Payload={action?:string;name?:string;code?:string;branchId?:string;fromWarehouseId?:string;toWarehouseId?:string;warehouseId?:string;productId?:string;variantId?:string;quantity?:number;countedQuantity?:number;minimumStock?:number;transferId?:string;lotNumber?:string;expirationDate?:string;laboratory?:string;healthRegistration?:string;serialNumber?:string;warrantyMonths?:number;unit?:string;conversionFactor?:number;barcode?:string;salePrice?:number;notes?:string;reason?:string;unitCostMinor?:number};
export async function POST(req:Request){
  const access=await requireAccess(req,"inventory","create");if(access.error)return access.error;
  const p=(await req.json()) as Payload,d=getRuntimeEnv().DB,T=access.user.tenantId,B=access.user.branchId,userId=access.user.id;
  const owns=async(table:"branches"|"warehouses"|"products"|"stock_transfers",id?:string)=>!id||Boolean(await d.prepare(`SELECT id FROM ${table} WHERE id=? AND tenant_id=?`).bind(id,T).first());
  if((await Promise.all([owns("branches",p.branchId),owns("warehouses",p.fromWarehouseId),owns("warehouses",p.toWarehouseId),owns("warehouses",p.warehouseId),owns("products",p.productId),owns("stock_transfers",p.transferId)])).some(x=>!x))return Response.json({error:"El recurso no pertenece a la empresa activa"},{status:403});
  try{
    if(p.action==="warehouse"){if(!p.name?.trim()||!p.code?.trim())return Response.json({error:"Nombre y código requeridos"},{status:400});const id=randomUUID();await d.prepare("INSERT INTO warehouses (id,tenant_id,branch_id,name,code) VALUES (?,?,?,?,?)").bind(id,T,p.branchId||B,p.name.trim(),p.code.trim()).run();return Response.json({id},{status:201})}
    if(p.action==="adjustment"){
      if(!["owner","admin","supervisor"].includes(access.user.role))return Response.json({error:"El ajuste requiere autorización de supervisor o administrador"},{status:403});
      if(!p.warehouseId||!p.productId||!p.quantity||!p.reason?.trim())return Response.json({error:"Bodega, producto, cantidad y motivo son obligatorios"},{status:400});
      const m=await inventoryMovement({tenantId:T,branchId:B,warehouseId:p.warehouseId,productId:p.productId,variantId:p.variantId,userId,movementType:p.quantity>0?"adjustment_in":"adjustment_out",quantity:Number(p.quantity),reason:p.reason,reference:`AJ-${Date.now()}`,sourceType:"adjustment",allowNegative:await negativeStockAllowed(T),unitCostMinor:p.unitCostMinor});await d.batch(m.statements);return Response.json({balanceAfter:m.after});
    }
    if(p.action==="minimum"){if(!p.warehouseId||!p.productId||Number(p.minimumStock)<0)return Response.json({error:"Datos de stock mínimo inválidos"},{status:400});await d.prepare("INSERT INTO inventory_balances (id,tenant_id,warehouse_id,product_id,variant_id,minimum_stock) VALUES (?,?,?,?,?,?) ON CONFLICT DO UPDATE SET minimum_stock=excluded.minimum_stock,updated_at=CURRENT_TIMESTAMP").bind(randomUUID(),T,p.warehouseId,p.productId,p.variantId||null,Number(p.minimumStock||0)).run();return Response.json({updated:true})}
    if(p.action==="transfer"){
      if(!p.fromWarehouseId||!p.toWarehouseId||!p.productId||Number(p.quantity)<=0||p.fromWarehouseId===p.toWarehouseId)return Response.json({error:"Complete origen, destino, producto y cantidad"},{status:400});
      const id=randomUUID(),number=`TR-${Date.now().toString().slice(-7)}`,qty=Number(p.quantity),out=await inventoryMovement({tenantId:T,branchId:B,warehouseId:p.fromWarehouseId,productId:p.productId,variantId:p.variantId,userId,movementType:"transfer_out",quantity:-qty,reason:p.reason?.trim()||`Traslado ${number} enviado`,reference:number,sourceType:"transfer",sourceId:id});
      await d.batch([d.prepare("INSERT INTO stock_transfers (id,tenant_id,from_warehouse_id,to_warehouse_id,user_id,number,status,notes) VALUES (?,?,?,?,?,?,'sent',?)").bind(id,T,p.fromWarehouseId,p.toWarehouseId,userId,number,p.notes||null),d.prepare("INSERT INTO stock_transfer_lines (id,transfer_id,product_id,quantity,unit_cost_minor) VALUES (?,?,?,?,?)").bind(randomUUID(),id,p.productId,qty,out.averageCostMinor),...out.statements]);return Response.json({id,number},{status:201});
    }
    if(p.action==="receive"){
      const tr=await d.prepare("SELECT id,to_warehouse_id toWarehouseId,number FROM stock_transfers WHERE id=? AND tenant_id=? AND status='sent'").bind(p.transferId,T).first<{id:string;toWarehouseId:string;number:string}>();if(!tr)return Response.json({error:"Traslado no disponible"},{status:404});
      const lines=await d.prepare("SELECT product_id productId,quantity,unit_cost_minor unitCostMinor FROM stock_transfer_lines WHERE transfer_id=?").bind(tr.id).all<{productId:string;quantity:number;unitCostMinor:number}>(),statements=[d.prepare("UPDATE stock_transfers SET status='received',received_at=CURRENT_TIMESTAMP WHERE id=?").bind(tr.id)];
      for(const line of lines.results){const m=await inventoryMovement({tenantId:T,branchId:B,warehouseId:tr.toWarehouseId,productId:line.productId,userId,movementType:"transfer_in",quantity:line.quantity,reason:`Recepción traslado ${tr.number}`,reference:tr.number,sourceType:"transfer",sourceId:tr.id,unitCostMinor:line.unitCostMinor});statements.push(...m.statements)}await d.batch(statements);return Response.json({received:true});
    }
    if(p.action==="count"){
      if(!p.warehouseId||!p.productId||p.countedQuantity===undefined||!p.reason?.trim())return Response.json({error:"Bodega, producto, conteo y motivo son obligatorios"},{status:400});
      const current=await d.prepare("SELECT quantity FROM inventory_balances WHERE warehouse_id=? AND product_id=? AND IFNULL(variant_id,'')=?").bind(p.warehouseId,p.productId,p.variantId||"").first<{quantity:number}>(),system=Number(current?.quantity||0),counted=Number(p.countedQuantity),diff=counted-system,id=randomUUID(),number=`CF-${Date.now().toString().slice(-7)}`,statements=[d.prepare("INSERT INTO stock_counts (id,tenant_id,warehouse_id,user_id,number,status,notes,completed_at) VALUES (?,?,?,?,?,'completed',?,CURRENT_TIMESTAMP)").bind(id,T,p.warehouseId,userId,number,p.reason),d.prepare("INSERT INTO stock_count_lines (id,count_id,product_id,system_quantity,counted_quantity,difference) VALUES (?,?,?,?,?,?)").bind(randomUUID(),id,p.productId,system,counted,diff)];
      if(diff){const m=await inventoryMovement({tenantId:T,branchId:B,warehouseId:p.warehouseId,productId:p.productId,variantId:p.variantId,userId,movementType:"physical_count",quantity:diff,reason:p.reason,reference:number,sourceType:"count",sourceId:id,allowNegative:await negativeStockAllowed(T)});statements.push(...m.statements)}await d.batch(statements);return Response.json({number,difference:diff});
    }
    if(p.action==="lot"){if(!p.warehouseId||!p.productId||!p.lotNumber?.trim())return Response.json({error:"Bodega, producto y lote requeridos"},{status:400});const id=randomUUID(),qty=Number(p.quantity||0),statements=[d.prepare("INSERT INTO product_lots (id,tenant_id,warehouse_id,product_id,lot_number,expiration_date,laboratory,health_registration,quantity) VALUES (?,?,?,?,?,?,?,?,?)").bind(id,T,p.warehouseId,p.productId,p.lotNumber,p.expirationDate||null,p.laboratory||null,p.healthRegistration||null,qty)];if(qty>0){const m=await inventoryMovement({tenantId:T,branchId:B,warehouseId:p.warehouseId,productId:p.productId,userId,movementType:"lot_entry",quantity:qty,reason:p.reason?.trim()||`Entrada lote ${p.lotNumber}`,reference:p.lotNumber,sourceType:"lot",sourceId:id,unitCostMinor:p.unitCostMinor});statements.push(...m.statements)}await d.batch(statements);return Response.json({id},{status:201})}
    if(p.action==="serial"){if(!p.warehouseId||!p.productId||!p.serialNumber?.trim())return Response.json({error:"Bodega, producto y serie requeridos"},{status:400});const id=randomUUID();await d.prepare("INSERT INTO product_serials (id,tenant_id,warehouse_id,product_id,serial_number,warranty_months) VALUES (?,?,?,?,?,?)").bind(id,T,p.warehouseId,p.productId,p.serialNumber,Number(p.warrantyMonths||0)).run();return Response.json({id},{status:201})}
    if(p.action==="presentation"){if(!p.productId||!p.name||!p.unit)return Response.json({error:"Producto, presentación y unidad requeridos"},{status:400});const id=randomUUID();await d.prepare("INSERT INTO product_presentations (id,tenant_id,product_id,name,unit,conversion_factor,barcode,sale_price) VALUES (?,?,?,?,?,?,?,?)").bind(id,T,p.productId,p.name,p.unit,Number(p.conversionFactor||1),p.barcode||null,Number(p.salePrice||0)).run();return Response.json({id},{status:201})}
    return Response.json({error:"Acción inválida"},{status:400});
  }catch(error){return Response.json({error:error instanceof Error?error.message:"No fue posible modificar el inventario"},{status:409})}
}
