import {randomUUID} from "node:crypto";
/* eslint-disable @typescript-eslint/no-explicit-any */
import {requireAccess} from "../../../db/authz";
import {getRuntimeEnv} from "../../../db/runtime-env";
import {multiplyMoney} from "../../../db/money";
import {PATCH as purchasePatch} from "../purchases/route";

const sha=async(value:string)=>Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value)))).map(x=>x.toString(16).padStart(2,"0")).join("");
async function device(req:Request){const token=(req.headers.get("authorization")||"").replace(/^Bearer\s+/i,"");if(!token)return null;const d=getRuntimeEnv().DB,result=await d.prepare("SELECT m.id,m.tenant_id tenantId,m.branch_id branchId,m.user_id userId,m.permissions,m.status,u.email,u.display_name displayName,t.name company,b.name branch FROM mobile_devices m JOIN app_users u ON u.id=m.user_id AND u.active=1 JOIN tenants t ON t.id=m.tenant_id AND t.status!='suspended' JOIN branches b ON b.id=m.branch_id WHERE m.token_hash=? AND m.status='active'").bind(await sha(token)).first<any>();if(result)await d.prepare("UPDATE mobile_devices SET last_seen_at=CURRENT_TIMESTAMP WHERE id=?").bind(result.id).run();return result}
const permitted=(credential:any,permission:string)=>JSON.parse(credential.permissions||"[]").includes(permission);

export async function GET(req:Request){
  const credential=await device(req),d=getRuntimeEnv().DB;
  if(req.headers.has("authorization")&&!credential)return Response.json({error:"Credencial móvil inválida o revocada"},{status:401});
  if(!credential){const access=await requireAccess(req,"settings");if(access.error)return access.error;const T=access.user.tenantId,[devices,backups,pilots,training,telemetry,users,branches]=await Promise.all([d.prepare("SELECT m.id,m.name,m.platform,m.device_identifier deviceIdentifier,m.app_version appVersion,m.status,m.permissions,m.last_seen_at lastSeenAt,m.last_sync_at lastSyncAt,u.display_name userName,b.name branchName FROM mobile_devices m JOIN app_users u ON u.id=m.user_id JOIN branches b ON b.id=m.branch_id WHERE m.tenant_id=? ORDER BY m.created_at DESC").bind(T).all(),d.prepare("SELECT id,backup_type backupType,status,schema_version schemaVersion,checksum_sha256 checksum,size_bytes sizeBytes,created_at createdAt,restored_at restoredAt FROM tenant_backups WHERE tenant_id=? ORDER BY created_at DESC LIMIT 20").bind(T).all(),d.prepare("SELECT id,name,contact_name contactName,contact_phone contactPhone,status,starts_at startsAt,ends_at endsAt,success_criteria successCriteria,observations FROM commercial_pilots WHERE tenant_id=? ORDER BY starts_at DESC").bind(T).all(),d.prepare("SELECT x.id,x.title,x.audience,x.scheduled_at scheduledAt,x.status,x.attendance,x.materials,x.notes,p.name pilotName FROM training_sessions x LEFT JOIN commercial_pilots p ON p.id=x.pilot_id WHERE x.tenant_id=? ORDER BY x.scheduled_at DESC").bind(T).all(),d.prepare("SELECT m.event_type eventType,m.level,m.payload,m.app_version appVersion,m.created_at createdAt,d.name deviceName FROM mobile_telemetry m JOIN mobile_devices d ON d.id=m.device_id WHERE m.tenant_id=? ORDER BY m.created_at DESC LIMIT 100").bind(T).all(),d.prepare("SELECT id,display_name displayName,role FROM app_users WHERE tenant_id=? AND active=1 ORDER BY display_name").bind(T).all(),d.prepare("SELECT id,name FROM branches WHERE tenant_id=? ORDER BY name").bind(T).all()]);return Response.json({devices:devices.results,backups:backups.results,pilots:pilots.results,training:training.results,telemetry:telemetry.results,users:users.results,branches:branches.results})}
  const T=credential.tenantId,B=credential.branchId,[products,warehouses,orders,purchases,alerts,mobileOrders]=await Promise.all([
    d.prepare("SELECT p.id,p.sku,p.barcode,p.name,p.category,p.price_minor priceMinor,p.cost_minor costMinor,p.track_inventory trackInventory,p.version,COALESCE((SELECT SUM(i.quantity) FROM inventory_balances i JOIN warehouses w ON w.id=i.warehouse_id WHERE i.product_id=p.id AND w.branch_id=?),0) stock FROM products p WHERE p.tenant_id=? AND p.active=1 ORDER BY p.name").bind(B,T).all(),
    d.prepare("SELECT id,name,code FROM warehouses WHERE tenant_id=? AND branch_id=? AND active=1 ORDER BY name").bind(T,B).all(),
    d.prepare("SELECT o.id,o.number,o.status,o.total_minor totalMinor,o.created_at createdAt,s.name supplierName,(SELECT SUM(quantity-received_quantity) FROM purchase_order_lines l WHERE l.order_id=o.id) pendingUnits FROM purchase_orders o JOIN suppliers s ON s.id=o.supplier_id WHERE o.tenant_id=? AND o.branch_id=? AND o.status IN ('approved','partial') ORDER BY o.created_at").bind(T,B).all(),
    d.prepare("SELECT l.id lineId,l.order_id orderId,l.product_id productId,p.name productName,p.sku,l.quantity,l.received_quantity receivedQuantity,l.quantity-l.received_quantity pendingQuantity FROM purchase_order_lines l JOIN purchase_orders o ON o.id=l.order_id JOIN products p ON p.id=l.product_id WHERE o.tenant_id=? AND o.branch_id=? AND o.status IN ('approved','partial') AND l.received_quantity<l.quantity ORDER BY o.created_at,p.name").bind(T,B).all(),
    d.prepare("SELECT id,alert_type alertType,severity,title,message,entity_type entityType,entity_id entityId,status,created_at createdAt FROM mobile_alerts WHERE tenant_id=? AND (branch_id IS NULL OR branch_id=?) AND status='open' ORDER BY CASE severity WHEN 'critical' THEN 0 WHEN 'warning' THEN 1 ELSE 2 END,created_at DESC").bind(T,B).all(),
    d.prepare("SELECT o.id,o.number,o.status,o.total_minor totalMinor,o.notes,o.created_at createdAt,COALESCE(c.name,'Sin cliente') customerName FROM mobile_orders o LEFT JOIN customers c ON c.id=o.customer_id WHERE o.tenant_id=? AND o.branch_id=? ORDER BY o.created_at DESC LIMIT 50").bind(T,B).all(),
  ]);await d.prepare("UPDATE mobile_devices SET last_sync_at=CURRENT_TIMESTAMP WHERE id=?").bind(credential.id).run();return Response.json({session:{deviceId:credential.id,userName:credential.displayName,company:credential.company,branch:credential.branch,permissions:JSON.parse(credential.permissions)},products:products.results,warehouses:warehouses.results,purchaseOrders:orders.results,purchaseLines:purchases.results,alerts:alerts.results,mobileOrders:mobileOrders.results,serverTime:new Date().toISOString(),appMinimumVersion:"1.0.0"});
}

type Body={action?:string;deviceName?:string;deviceIdentifier?:string;userId?:string;branchId?:string;permissions?:string[];appVersion?:string;operationId?:string;orderId?:string;lines?:{lineId?:string;productId?:string;quantity:number}[];reason?:string;customerId?:string;notes?:string;alertId?:string;eventType?:string;level?:string;payload?:unknown;name?:string;contactName?:string;contactPhone?:string;startsAt?:string;endsAt?:string;successCriteria?:string;pilotId?:string;title?:string;audience?:string;scheduledAt?:string;materials?:string[];backupId?:string;confirmation?:string};
export async function POST(req:Request){
  const body=await req.json() as Body,d=getRuntimeEnv().DB,credential=await device(req);
  if(req.headers.has("authorization")&&!credential)return Response.json({error:"Credencial móvil inválida o revocada"},{status:401});
  if(!credential){const access=await requireAccess(req,"settings","create");if(access.error)return access.error;const T=access.user.tenantId;if(body.action==="provision"){if(!["owner","admin"].includes(access.user.role)||!body.deviceName?.trim()||!body.deviceIdentifier?.trim()||!body.userId||!body.branchId)return Response.json({error:"Complete dispositivo, usuario y sede"},{status:400});const [user,branch]=await Promise.all([d.prepare("SELECT id FROM app_users WHERE id=? AND tenant_id=? AND active=1").bind(body.userId,T).first(),d.prepare("SELECT id FROM branches WHERE id=? AND tenant_id=?").bind(body.branchId,T).first()]);if(!user||!branch)return Response.json({error:"Usuario o sede no pertenece a la empresa"},{status:403});const id=randomUUID(),token=`mob_${crypto.randomUUID().replaceAll("-","")}`;await d.prepare("INSERT INTO mobile_devices(id,tenant_id,branch_id,user_id,name,device_identifier,token_hash,app_version,permissions,created_by) VALUES(?,?,?,?,?,?,?,?,?,?)").bind(id,T,body.branchId,body.userId,body.deviceName.trim(),body.deviceIdentifier.trim(),await sha(token),body.appVersion||null,JSON.stringify(body.permissions||["inventory:view","purchases:receive","orders:create","alerts:view"]),access.user.id).run();return Response.json({device:{id,token},warning:"El token se muestra una sola vez"},{status:201})}
    if(body.action==="backup"){if(!["owner","admin"].includes(access.user.role))return Response.json({error:"Solo administración crea copias"},{status:403});return createBackup(T,access.user.id,"logical")}
    if(body.action==="restore"){if(access.user.role!=="owner"||body.confirmation!==`RESTORE ${T}`||!body.backupId)return Response.json({error:`La restauración requiere propietario y confirmación RESTORE ${T}`},{status:403});const backup=await d.prepare("SELECT payload FROM tenant_backups WHERE id=? AND tenant_id=? AND status='completed'").bind(body.backupId,T).first<{payload:string}>();if(!backup)return Response.json({error:"Copia no disponible"},{status:404});await createBackup(T,access.user.id,"pre_restore");const snapshot=JSON.parse(backup.payload) as any,statements=[];for(const product of snapshot.products||[])statements.push(d.prepare("UPDATE products SET name=?,category=?,price_minor=?,cost_minor=?,active=?,version=version+1,updated_at=CURRENT_TIMESTAMP WHERE id=? AND tenant_id=?").bind(product.name,product.category,product.priceMinor,product.costMinor,product.active,product.id,T));for(const balance of snapshot.balances||[])statements.push(d.prepare("UPDATE inventory_balances SET quantity=?,average_cost_minor=?,minimum_stock=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND tenant_id=?").bind(balance.quantity,balance.averageCostMinor,balance.minimumStock,balance.id,T));statements.push(d.prepare("UPDATE tenant_backups SET status='restored',restored_at=CURRENT_TIMESTAMP WHERE id=?").bind(body.backupId));await d.batch(statements);return Response.json({restored:true,products:(snapshot.products||[]).length,balances:(snapshot.balances||[]).length})}
    if(body.action==="pilot"){if(!body.name||!body.contactName||!body.startsAt||!body.successCriteria)return Response.json({error:"Complete nombre, contacto, fecha y criterios"},{status:400});const id=randomUUID();await d.prepare("INSERT INTO commercial_pilots(id,tenant_id,name,contact_name,contact_phone,starts_at,ends_at,success_criteria,created_by) VALUES(?,?,?,?,?,?,?,?,?)").bind(id,T,body.name,body.contactName,body.contactPhone||null,body.startsAt,body.endsAt||null,body.successCriteria,access.user.id).run();return Response.json({id},{status:201})}
    if(body.action==="training"){if(!body.title||!body.audience||!body.scheduledAt)return Response.json({error:"Complete capacitación, audiencia y fecha"},{status:400});if(body.pilotId&&!await d.prepare("SELECT id FROM commercial_pilots WHERE id=? AND tenant_id=?").bind(body.pilotId,T).first())return Response.json({error:"Piloto inválido"},{status:403});const id=randomUUID();await d.prepare("INSERT INTO training_sessions(id,tenant_id,pilot_id,title,audience,scheduled_at,materials,created_by) VALUES(?,?,?,?,?,?,?,?)").bind(id,T,body.pilotId||null,body.title,body.audience,body.scheduledAt,JSON.stringify(body.materials||[]),access.user.id).run();return Response.json({id},{status:201})}
    return Response.json({error:"Acción administrativa móvil inválida"},{status:400});
  }
  const T=credential.tenantId,B=credential.branchId,user=credential.userId;if(!body.operationId)return Response.json({error:"operationId idempotente requerido"},{status:400});const previous=await d.prepare("SELECT status,result FROM mobile_operations WHERE device_id=? AND operation_id=?").bind(credential.id,body.operationId).first<{status:string;result:string}>();if(previous)return Response.json({status:previous.status,result:previous.result?JSON.parse(previous.result):null,duplicate:true});let result:any,status="applied";
  try{
    if(body.action==="receive_purchase"){if(!permitted(credential,"purchases:receive"))return Response.json({error:"Dispositivo sin permiso para recibir compras"},{status:403});const forwarded=new Request("http://localhost/api/purchases",{method:"PATCH",headers:{"content-type":"application/json","oai-authenticated-user-email":credential.email,"x-pos360-tenant-id":T,"x-pos360-branch-id":B},body:JSON.stringify({action:"receive",orderId:body.orderId,lines:body.lines,reason:body.reason||"Recepción desde Android"})}),response=await purchasePatch(forwarded);result=await response.json();if(!response.ok){status="rejected";throw new Error(String(result.error||"Recepción rechazada"))}}
    else if(body.action==="order"){if(!permitted(credential,"orders:create")||!body.lines?.length)return Response.json({error:"Pedido vacío o dispositivo sin permiso"},{status:403});let totalMinor=0;const normalized=[];for(const line of body.lines){const product=await d.prepare("SELECT id,price_minor priceMinor FROM products WHERE id=? AND tenant_id=? AND active=1").bind(line.productId,T).first<{id:string;priceMinor:number}>();if(!product||Number(line.quantity)<=0)return Response.json({error:"Producto o cantidad inválida"},{status:400});const lineTotalMinor=multiplyMoney(product.priceMinor,Number(line.quantity));totalMinor+=lineTotalMinor;normalized.push({...line,priceMinor:product.priceMinor,lineTotalMinor})}const id=randomUUID(),number=`PED-M-${Date.now().toString().slice(-8)}`;await d.batch([d.prepare("INSERT INTO mobile_orders(id,tenant_id,branch_id,device_id,user_id,customer_id,number,notes,total_minor) VALUES(?,?,?,?,?,?,?,?,?)").bind(id,T,B,credential.id,user,body.customerId||null,number,body.notes||null,totalMinor),...normalized.map(line=>d.prepare("INSERT INTO mobile_order_lines(id,order_id,product_id,quantity,unit_price_minor,line_total_minor) VALUES(?,?,?,?,?,?)").bind(randomUUID(),id,line.productId,line.quantity,line.priceMinor,line.lineTotalMinor))]);result={order:{id,number,totalMinor,status:"pending"}}}
    else if(body.action==="ack_alert"){if(!permitted(credential,"alerts:view"))return Response.json({error:"Sin permiso de alertas"},{status:403});await d.prepare("UPDATE mobile_alerts SET status='acknowledged',acknowledged_by=?,acknowledged_at=CURRENT_TIMESTAMP WHERE id=? AND tenant_id=? AND (branch_id IS NULL OR branch_id=?)").bind(user,body.alertId,T,B).run();result={acknowledged:true}}
    else if(body.action==="telemetry"){await d.prepare("INSERT INTO mobile_telemetry(id,tenant_id,device_id,event_type,level,payload,app_version) VALUES(?,?,?,?,?,?,?)").bind(randomUUID(),T,credential.id,body.eventType||"app.event",["info","warning","error"].includes(body.level||"")?body.level:"info",JSON.stringify(body.payload||{}),body.appVersion||null).run();result={recorded:true}}
    else return Response.json({error:"Operación móvil inválida"},{status:400});
  }catch(error){status="rejected";result={error:error instanceof Error?error.message:"Operación rechazada"}}
  await d.batch([d.prepare("INSERT INTO mobile_operations(id,tenant_id,device_id,operation_id,operation_type,payload,status,result,applied_at) VALUES(?,?,?,?,?,?,?,?,CASE WHEN ?='applied' THEN CURRENT_TIMESTAMP ELSE NULL END)").bind(randomUUID(),T,credential.id,body.operationId,body.action||"unknown",JSON.stringify(body),status,JSON.stringify(result),status),d.prepare("INSERT INTO sync_events(id,tenant_id,node_id,event_type,entity_id,payload,status) VALUES(?,?,?,?,?,?,?)").bind(randomUUID(),T,credential.id,`mobile.${body.action}`,body.operationId,JSON.stringify(result),status)]);return Response.json({status,result},{status:status==="applied"?201:409});
}

async function createBackup(tenantId:string,userId:string,type:string){const d=getRuntimeEnv().DB,[settings,products,balances]=await Promise.all([d.prepare("SELECT nit,sector,currency,timezone,allow_negative_stock allowNegativeStock,receipt_format receiptFormat FROM business_settings WHERE tenant_id=?").bind(tenantId).first(),d.prepare("SELECT id,sku,name,category,price_minor priceMinor,cost_minor costMinor,active FROM products WHERE tenant_id=?").bind(tenantId).all(),d.prepare("SELECT id,warehouse_id warehouseId,product_id productId,quantity,average_cost_minor averageCostMinor,minimum_stock minimumStock FROM inventory_balances WHERE tenant_id=?").bind(tenantId).all()]),payload=JSON.stringify({schemaVersion:"0023",createdAt:new Date().toISOString(),settings,products:products.results,balances:balances.results}),checksum=await sha(payload),id=randomUUID();await d.prepare("INSERT INTO tenant_backups(id,tenant_id,backup_type,schema_version,payload,checksum_sha256,size_bytes,created_by) VALUES(?,?,?,?,?,?,?,?)").bind(id,tenantId,type,"0023",payload,checksum,new TextEncoder().encode(payload).length,userId).run();return Response.json({backup:{id,checksum,sizeBytes:new TextEncoder().encode(payload).length}},{status:201})}
