"use client";
/* eslint-disable @typescript-eslint/no-explicit-any */
import { useEffect,useState } from "react";
import { readJson } from "./api-client";
const money=(n:number)=>new Intl.NumberFormat("es-CO",{style:"currency",currency:"COP",maximumFractionDigits:2}).format(n||0);
type Customer={id:string;documentType:string;documentNumber:string;name:string;commercialName?:string;phone?:string;email?:string;creditLimit:number;creditDays:number;priceListId?:string;priceListName?:string;balance:number;overdue:number;nextDue:string;blocked:number;blockReason?:string;consentEmail:number;consentSms:number;consentWhatsapp:number;active:number};
type Modal="new"|"edit"|"payment"|"address"|"authorize"|"consent"|"block"|"detail"|null;
const empty={documentType:"CC",documentNumber:"",name:"",commercialName:"",phone:"",email:"",creditLimit:"0",creditDays:"30",priceListId:"",notes:"",address:{label:"Principal",address:"",city:"Cúcuta",state:"Norte de Santander",postalCode:"",country:"CO"},consentEmail:false,consentSms:false,consentWhatsapp:false,consentSource:"Autorización del titular"};
export default function Customers({notify}:{notify:(s:string)=>void}){
 const [items,setItems]=useState<Customer[]>([]),[summary,setSummary]=useState<any>({}),[priceLists,setPriceLists]=useState<any[]>([]),[q,setQ]=useState(""),[modal,setModal]=useState<Modal>(null),[selected,setSelected]=useState<Customer|null>(null),[detail,setDetail]=useState<any>(null),[form,setForm]=useState<any>(empty),[payment,setPayment]=useState({amount:"",method:"cash",reference:"",reason:"Abono de cartera"}),[address,setAddress]=useState({label:"Principal",address:"",city:"Cúcuta",state:"Norte de Santander",postalCode:"",country:"CO",isDefault:true}),[authorization,setAuthorization]=useState({amount:"",reason:"",expiresHours:"24"}),[blockReason,setBlockReason]=useState("");
 const load=async()=>{const [c,p]=await Promise.all([fetch(`/api/customers?q=${encodeURIComponent(q)}`),fetch("/api/products")]),[cd,pd]=await Promise.all([readJson<any>(c),readJson<any>(p)]);setItems(cd.customers||[]);setSummary(cd.summary||{});setPriceLists(pd.priceLists||[])};useEffect(()=>{load()},[q]);
 const request=async(method:string,body:any)=>{const r=await fetch("/api/customers",{method,headers:{"content-type":"application/json"},body:JSON.stringify(body)}),d=await readJson<any>(r);if(!r.ok){notify(d.error);return null}return d};
 const save=async()=>{const body={...form,creditLimit:form.creditLimit,creditDays:Number(form.creditDays)};const d=await request(modal==="new"?"POST":"PATCH",modal==="new"?body:{...body,id:selected?.id,action:"profile"});if(d){setModal(null);notify(modal==="new"?"Cliente creado correctamente":"Perfil comercial actualizado");load()}};
 const patch=async(action:string,extra:any)=>{if(!selected)return;const d=await request("PATCH",{id:selected.id,action,...extra});if(d){setModal(null);notify(action==="payment"?`Abono aplicado. Saldo ${money(d.payment.remaining)}`:action==="authorize_credit"?"Excepción de crédito autorizada":action==="address"?"Dirección registrada":action==="block"?(d.blocked?"Cliente bloqueado":"Cliente desbloqueado"):"Consentimiento actualizado");load()}};
 const openDetail=async(c:Customer)=>{setSelected(c);const r=await fetch(`/api/customers?customerId=${c.id}`),d=await readJson<any>(r);setDetail(d);setModal("detail")};
 const edit=(c:Customer)=>{setSelected(c);setForm({...empty,...c,creditLimit:String(c.creditLimit),creditDays:String(c.creditDays),notes:""});setModal("edit")};
 return <><div className="page-intro"><div><h2>Clientes y cartera</h2><p>Perfil comercial, crédito, abonos, vencimientos, bloqueos y comunicaciones autorizadas.</p></div><button className="primary" onClick={()=>{setForm({...empty,address:{...empty.address}});setModal("new")}}>+ Nuevo cliente</button></div>
 <div className="summary-strip"><K label="Clientes activos" value={String(items.filter(x=>x.active).length)} tone="blue"/><K label="Cartera total" value={money(summary.total)} tone="purple"/><K label="Cartera vencida" value={money(summary.overdue)} tone="orange"/><K label="Cuentas abiertas" value={String(summary.openAccounts||0)} tone="green"/></div>
 <article className="panel table-panel"><div className="filters"><div className="table-search">⌕<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar nombre, razón comercial, documento o teléfono"/></div><span className="db-badge">● Estado de cartera actualizado</span></div><table><thead><tr><th>Cliente</th><th>Contacto</th><th>Condiciones</th><th>Saldo / vencido</th><th>Comunicaciones</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{items.length?items.map(c=><tr key={c.id}><td><button className="table-action" onClick={()=>openDetail(c)}><b>{c.name}</b></button><small className="cell-sub">{c.commercialName||`${c.documentType} ${c.documentNumber}`}</small></td><td>{c.phone||"—"}<small className="cell-sub">{c.email||"Sin correo"}</small></td><td>Cupo {money(c.creditLimit)}<small className="cell-sub">{c.creditDays} días · {c.priceListName||"Precio general"}</small></td><td><b>{money(c.balance)}</b><small className={c.overdue?"cell-sub debt":"cell-sub"}>Vencido {money(c.overdue)}</small></td><td>{[c.consentEmail&&"Email",c.consentSms&&"SMS",c.consentWhatsapp&&"WhatsApp"].filter(Boolean).join(" · ")||"Sin autorización"}</td><td><span className={c.blocked||c.overdue?"status low":"status ok"}>{c.blocked?"Bloqueado":c.overdue?"Vencido":"Al día"}</span></td><td><div className="row-actions"><button className="table-action" onClick={()=>edit(c)}>Editar</button>{c.balance>0&&<button className="table-action" onClick={()=>{setSelected(c);setPayment({amount:String(c.balance),method:"cash",reference:"",reason:"Abono de cartera"});setModal("payment")}}>Abonar</button>}<button className="table-action" onClick={()=>{setSelected(c);setBlockReason(c.blockReason||"");setModal("block")}}>{c.blocked?"Desbloquear":"Bloquear"}</button></div></td></tr>):<tr><td colSpan={7}>Cree el primer cliente para comenzar.</td></tr>}</tbody></table></article>
 {items.some(x=>x.overdue>0)&&<article className="panel table-panel returns-panel"><div className="filters"><b>Cartera vencida</b><span className="status low">Requiere seguimiento</span></div><table><thead><tr><th>Cliente</th><th>Próximo vencimiento</th><th>Vencido</th><th>Contacto</th><th>Acción</th></tr></thead><tbody>{items.filter(x=>x.overdue>0).map(c=><tr key={c.id}><td><b>{c.name}</b></td><td>{c.nextDue||"—"}</td><td className="debt">{money(c.overdue)}</td><td>{c.phone||c.email||"—"}</td><td><button className="table-action" onClick={()=>openDetail(c)}>Estado de cuenta</button></td></tr>)}</tbody></table></article>}
 {modal&&<div className="modal-backdrop" onMouseDown={()=>setModal(null)}><section className="modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><h3>{modal==="new"?"Nuevo cliente":modal==="edit"?"Editar perfil comercial":modal==="payment"?"Registrar abono":modal==="address"?"Nueva dirección":modal==="authorize"?"Autorizar excepción de crédito":modal==="consent"?"Consentimiento de comunicaciones":modal==="block"?(selected?.blocked?"Desbloquear cliente":"Bloquear cliente"):"Estado de cuenta"}</h3><p>{selected?.name||"Clientes POS360"}</p></div><button onClick={()=>setModal(null)}>×</button></div>
 {(modal==="new"||modal==="edit")?<div className="payment-body"><div className="form-grid"><label>Tipo de documento<select value={form.documentType} onChange={e=>setForm({...form,documentType:e.target.value})} disabled={modal==="edit"}><option>CC</option><option>NIT</option><option>CE</option><option>Pasaporte</option></select></label><label>Número de documento<input value={form.documentNumber} onChange={e=>setForm({...form,documentNumber:e.target.value})} disabled={modal==="edit"}/></label><label>Nombre o razón social<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Nombre comercial<input value={form.commercialName} onChange={e=>setForm({...form,commercialName:e.target.value})}/></label><label>Teléfono<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>Correo<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Cupo de crédito<input type="number" min="0" step="0.01" value={form.creditLimit} onChange={e=>setForm({...form,creditLimit:e.target.value})}/></label><label>Plazo en días<input type="number" min="0" max="365" value={form.creditDays} onChange={e=>setForm({...form,creditDays:e.target.value})}/></label><label>Lista de precios<select value={form.priceListId||""} onChange={e=>setForm({...form,priceListId:e.target.value})}><option value="">Precio general</option>{priceLists.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label></div>{modal==="new"&&<><h4>Dirección principal</h4><div className="form-grid"><label>Dirección<input value={form.address.address} onChange={e=>setForm({...form,address:{...form.address,address:e.target.value}})}/></label><label>Ciudad<input value={form.address.city} onChange={e=>setForm({...form,address:{...form.address,city:e.target.value}})}/></label></div><h4>Consentimiento expreso</h4><div className="row-actions"><label><input type="checkbox" checked={form.consentEmail} onChange={e=>setForm({...form,consentEmail:e.target.checked})}/> Email</label><label><input type="checkbox" checked={form.consentSms} onChange={e=>setForm({...form,consentSms:e.target.checked})}/> SMS</label><label><input type="checkbox" checked={form.consentWhatsapp} onChange={e=>setForm({...form,consentWhatsapp:e.target.checked})}/> WhatsApp</label></div></>}</div>
 :modal==="payment"?<div className="payment-body"><div className="receipt-total"><span>Cartera pendiente</span><b>{money(selected?.balance||0)}</b></div><label>Valor del abono<input type="number" min="0.01" step="0.01" value={payment.amount} onChange={e=>setPayment({...payment,amount:e.target.value})}/></label><label>Medio<select value={payment.method} onChange={e=>setPayment({...payment,method:e.target.value})}><option value="cash">Efectivo</option><option value="transfer">Transferencia</option><option value="card">Tarjeta</option><option value="check">Cheque</option></select></label><label>Referencia<input value={payment.reference} onChange={e=>setPayment({...payment,reference:e.target.value})}/></label></div>
 :modal==="address"?<div className="form-grid"><label>Etiqueta<input value={address.label} onChange={e=>setAddress({...address,label:e.target.value})}/></label><label>Dirección<input value={address.address} onChange={e=>setAddress({...address,address:e.target.value})}/></label><label>Ciudad<input value={address.city} onChange={e=>setAddress({...address,city:e.target.value})}/></label><label>Departamento<input value={address.state} onChange={e=>setAddress({...address,state:e.target.value})}/></label><label><input type="checkbox" checked={address.isDefault} onChange={e=>setAddress({...address,isDefault:e.target.checked})}/> Dirección principal</label></div>
 :modal==="authorize"?<div className="payment-body"><div className="success-box">Permite una próxima venta a crédito aunque el cliente esté bloqueado, vencido o exceda su cupo. Se consume una sola vez.</div><label>Monto autorizado<input type="number" min="0.01" value={authorization.amount} onChange={e=>setAuthorization({...authorization,amount:e.target.value})}/></label><label>Motivo obligatorio<input value={authorization.reason} onChange={e=>setAuthorization({...authorization,reason:e.target.value})}/></label><label>Vigencia<select value={authorization.expiresHours} onChange={e=>setAuthorization({...authorization,expiresHours:e.target.value})}><option value="1">1 hora</option><option value="8">8 horas</option><option value="24">24 horas</option><option value="72">72 horas</option></select></label></div>
 :modal==="consent"?<div className="payment-body"><label><input type="checkbox" checked={form.consentEmail} onChange={e=>setForm({...form,consentEmail:e.target.checked})}/> Autoriza correo electrónico</label><label><input type="checkbox" checked={form.consentSms} onChange={e=>setForm({...form,consentSms:e.target.checked})}/> Autoriza SMS</label><label><input type="checkbox" checked={form.consentWhatsapp} onChange={e=>setForm({...form,consentWhatsapp:e.target.checked})}/> Autoriza WhatsApp</label><label>Fuente del consentimiento<input value={form.consentSource} onChange={e=>setForm({...form,consentSource:e.target.value})}/></label></div>
 :modal==="block"?<div className="payment-body">{selected?.blocked?<div className="success-box">Se habilitará nuevamente el crédito ordinario del cliente.</div>:<label>Motivo obligatorio<input value={blockReason} onChange={e=>setBlockReason(e.target.value)}/></label>}</div>
 :<div className="payment-body">{detail?.customer&&<><div className="receipt-total"><span>Cupo disponible</span><b>{money(Math.max(0,detail.customer.creditLimit-detail.customer.balance))}</b></div><div className="row-actions"><button className="secondary" onClick={()=>{setAddress({label:"Principal",address:"",city:"Cúcuta",state:"Norte de Santander",postalCode:"",country:"CO",isDefault:true});setModal("address")}}>+ Dirección</button><button className="secondary" onClick={()=>{setAuthorization({amount:String(Math.max(detail.customer.balance,detail.customer.creditLimit)),reason:"",expiresHours:"24"});setModal("authorize")}}>Autorizar crédito</button><button className="secondary" onClick={()=>{setForm({...empty,consentEmail:Boolean(detail.customer.consentEmail),consentSms:Boolean(detail.customer.consentSms),consentWhatsapp:Boolean(detail.customer.consentWhatsapp),consentSource:detail.customer.consentSource||"Actualización del titular"});setModal("consent")}}>Comunicaciones</button></div><h4>Direcciones</h4>{(detail.addresses||[]).map((a:any)=><div className="supplier-aging" key={a.id}><div><b>{a.label}{a.isDefault?" · Principal":""}</b><small>{a.address}, {a.city}</small></div></div>)}<h4>Facturas y saldos</h4>{(detail.receivables||[]).map((r:any)=><div className="receipt-total" key={r.id}><span>{r.saleNumber}<small className="cell-sub">Vence {r.dueDate} · {r.status}</small></span><b>{money(r.balance)} / {money(r.originalAmount)}</b></div>)}<h4>Abonos</h4>{(detail.payments||[]).map((p:any)=><div className="supplier-aging" key={p.id}><div><b>{p.reference} · {p.userName}</b><small>{new Date(p.createdAt).toLocaleString("es-CO")} · {p.method}</small></div><strong>{money(p.amount)}</strong></div>)}{(detail.credits||[]).length>0&&<><h4>Saldos a favor</h4>{detail.credits.map((c:any)=><div className="receipt-total" key={c.id}><span>{c.reason}</span><b>{money(c.balance)}</b></div>)}</>}<h4>Historial</h4>{(detail.events||[]).map((e:any)=><div className="supplier-aging" key={e.id}><div><b>{e.action} · {e.userName}</b><small>{e.reason}</small></div><span>{new Date(e.createdAt).toLocaleDateString("es-CO")}</span></div>)}</>}</div>}
 {modal!=="detail"&&<div className="modal-actions"><button className="secondary" onClick={()=>setModal(null)}>Cancelar</button><button className="primary" onClick={()=>modal==="new"||modal==="edit"?save():modal==="payment"?patch("payment",payment):modal==="address"?patch("address",{address}):modal==="authorize"?patch("authorize_credit",{...authorization,expiresHours:Number(authorization.expiresHours)}):modal==="consent"?patch("consent",form):patch("block",{blocked:!selected?.blocked,reason:blockReason})}>{modal==="new"?"Guardar cliente":modal==="edit"?"Actualizar perfil":modal==="payment"?"Aplicar abono":modal==="address"?"Guardar dirección":modal==="authorize"?"Autorizar excepción":modal==="consent"?"Guardar consentimiento":selected?.blocked?"Desbloquear":"Bloquear"}</button></div>}</section></div>}
 </>;
}
function K({label,value,tone}:{label:string;value:string;tone:string}){return <div className="kpi"><div className={`kpi-icon ${tone}`}>◎</div><div><span>{label}</span><strong>{value}</strong><small>Clientes y cartera</small></div></div>}
