import Link from "next/link";

const modules=[["▣","Punto de venta","Ventas rápidas, códigos de barras, pagos combinados, crédito, devoluciones y protección contra duplicados."],["▦","Inventario y kardex","Existencias por bodega, movimientos trazables, conteos, traslados, alertas, lotes y vencimientos."],["↓","Compras y proveedores","Órdenes autorizadas, recepciones parciales, costos, cuentas por pagar y devoluciones."],["◎","Clientes y cartera","Cupos, plazos, ventas a crédito, abonos, estados de cuenta y vencimientos."],["◇","Caja y terminales","Aperturas, movimientos, arqueos, cierres, diferencias y aprobación."],["↗","Reportes reales","Ventas, utilidad, pagos, inventario valorizado, compras, caja y cartera."],["▤","Facturación electrónica","Numeraciones, documentos, notas, contingencias y seguimiento."],["↻","Operación offline","Windows y Android con cola durable, sincronización e idempotencia."]];
const sectors=[["Droguerías","Lotes, vencimientos, FEFO y fraccionamiento."],["Ferreterías","Medidas, calibres, cotizaciones y despachos parciales."],["Supermercados","Básculas, productos por peso, promociones y combos."],["Tiendas","Venta rápida, crédito sencillo, cartera y abonos."]];
const faqs=[["¿Cuánto dura la prueba gratuita?","Tendrá 15 días para configurar su negocio y probar las funciones disponibles antes de contratar."],["¿Cuánto cuesta POS360?","El plan inicial tendrá un valor de $60.000 COP mensuales. Los límites y condiciones serán visibles antes de contratar."],["¿Puedo usarlo sin internet?","El núcleo web necesita conexión. Windows y Android podrán continuar operaciones autorizadas y sincronizar después."],["¿Mis datos se mezclan con otras empresas?","No. Cada empresa, sede, usuario y operación se identifica y filtra independientemente."],["¿Sirve para varias sedes?","Sí. POS360 administra sedes, bodegas, cajas, terminales, usuarios y permisos."],["¿Incluye soporte?","Sí. La implementación comercial contempla capacitación, seguimiento y soporte."]];
const steps=[["01","Cree su empresa","Registre el negocio y confirme el correo del propietario."],["02","Configure la operación","Defina sede, bodega, caja, impuestos y políticas."],["03","Cargue su catálogo","Agregue productos, precios, costos e inventario inicial."],["04","Abra caja y venda","Registre ventas y consulte resultados reales."]];

export default function MarketingHome(){return <main className="marketing">
<header className="marketing-nav"><Link className="marketing-brand" href="/"><span>P</span><div><b>POS360</b><small>Gestión comercial</small></div></Link><nav><a href="#funciones">Funciones</a><a href="#sectores">Sectores</a><a href="#precio">Precio</a><a href="#preguntas">Preguntas</a></nav><div className="marketing-nav-actions"><Link className="marketing-login" href="/login">Iniciar sesión</Link><Link className="marketing-primary small" href="/registro">Probar gratis</Link></div></header>
<section className="hero"><div className="hero-copy"><span className="marketing-pill">VENTAS · INVENTARIO · CAJA · REPORTES</span><h1>Controle su negocio desde un solo lugar.</h1><p>POS360 conecta el punto de venta con inventario, compras, clientes, caja y reportes para tomar decisiones con información real.</p><div className="hero-actions"><Link className="marketing-primary" href="/registro">Comenzar prueba de 15 días</Link><a className="marketing-secondary" href="#como-funciona">Ver cómo funciona</a></div><div className="hero-trust"><span>✓ Sin tarjeta para iniciar</span><span>✓ Información por empresa</span><span>✓ Acompañamiento inicial</span></div></div><div className="hero-product"><div className="browser-bar"><i/><i/><i/><span>POS360 · Resumen operativo</span></div><div className="product-preview"><aside><b>P</b>{["Inicio","Punto de venta","Inventario","Compras","Clientes","Reportes"].map((x,i)=><span className={i===0?"active":""} key={x}>{x}</span>)}</aside><div><small>INFORMACIÓN EN TIEMPO REAL</small><h3>Resumen operativo de hoy</h3><div className="preview-kpis">{[["Ventas","$ 1.840.000"],["Ticket promedio","$ 46.000"],["Utilidad","$ 522.000"]].map(x=><article key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><small>Información actualizada</small></article>)}</div><div className="preview-chart"><div><b>Ventas de la semana</b><section>{[42,68,53,82,64,94,77].map((h,i)=><i key={i} style={{height:`${h}%`}}/>)}</section></div><aside><b>Alertas reales</b><span>3 productos con stock bajo</span><span>2 cuentas próximas a vencer</span><span>Caja operando correctamente</span></aside></div></div></div></div></section>
<section className="marketing-stats"><article><b>15 días</b><span>de prueba gratuita</span></article><article><b>$60.000</b><span>COP al mes</span></article><article><b>4 sectores</b><span>con funciones especializadas</span></article><article><b>Online + offline</b><span>según dispositivo autorizado</span></article></section>
<section className="marketing-section" id="funciones"><Heading tag="UN SISTEMA CONECTADO" title="Todo lo que necesita para operar con control" copy="Cada módulo comparte la misma empresa, sede, usuario y trazabilidad."/><div className="module-grid">{modules.map(x=><article key={x[1]}><i>{x[0]}</i><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
<section className="how" id="como-funciona"><div><span>IMPLEMENTACIÓN GUIADA</span><h2>De registro a primera venta en cuatro pasos</h2><p>POS360 prepara la estructura inicial y acompaña la configuración.</p></div><ol>{steps.map(x=><li key={x[0]}><b>{x[0]}</b><div><h3>{x[1]}</h3><p>{x[2]}</p></div></li>)}</ol></section>
<section className="marketing-section sector-section" id="sectores"><Heading tag="CRECE CON SU NEGOCIO" title="Herramientas según su sector" copy="Active solamente las capacidades que su operación necesita."/><div className="sector-cards">{sectors.map((x,i)=><article key={x[0]}><span>{["+","⌁","▦","▣"][i]}</span><h3>{x[0]}</h3><p>{x[1]}</p><b>Configuración especializada →</b></article>)}</div></section>
<section className="offline"><div><span>CONTINUIDAD OPERATIVA</span><h2>Su negocio no debería detenerse por una conexión inestable.</h2><p>Windows y Android están diseñados con identidad de terminal, almacenamiento local y sincronización protegida contra duplicados.</p><ul><li>Ventas locales transaccionales</li><li>Cola durable e idempotente</li><li>Recuperación después de reinicios</li><li>Monitoreo de sincronización</li></ul></div><div className="device-stage"><div className="desktop-device"><span>POS360 Windows</span><b>$ 86.500</b><small>Venta guardada localmente ✓</small></div><div className="phone-device"><span>POS360</span><b>Inventario</b><i>Sincronizado</i><small>24 productos revisados</small></div></div></section>
<section className="price-section" id="precio"><div className="price-copy"><span>PRECIO CLARO</span><h2>Empiece a organizar su negocio hoy.</h2><p>Pruebe POS360 durante 15 días. Sus datos se conservan si decide activar la suscripción.</p><ul><li>Punto de venta e inventario</li><li>Compras, clientes y cartera</li><li>Caja, reportes y auditoría</li><li>Actualizaciones y soporte</li></ul></div><article className="price-card"><span>PLAN POS360 COMERCIAL</span><div><b>$60.000</b><small>COP / mes</small></div><p>15 días de prueba gratuita</p><Link className="marketing-primary" href="/registro">Probar gratis</Link><small>No requiere tarjeta para comenzar. Condiciones visibles antes de contratar.</small></article></section>
<section className="marketing-section downloads"><Heading tag="APLICACIONES" title="POS360 donde trabaja su equipo" copy="Las descargas se habilitarán solamente después de completar firma y pruebas con dispositivos reales."/><div><Download icon="▣" title="POS360 para Windows" copy="Venta offline, impresión térmica, lector y sincronización."/><Download icon="A" title="POS360 para Android" copy="Inventario, recepción de compras, pedidos y alertas."/></div></section>
<section className="marketing-section faq" id="preguntas"><Heading tag="RESPUESTAS CLARAS" title="Preguntas frecuentes"/><div>{faqs.map(x=><details key={x[0]}><summary>{x[0]}<span>+</span></summary><p>{x[1]}</p></details>)}</div></section>
<section className="support-cta"><div><span>¿TIENE PREGUNTAS?</span><h2>Conversemos sobre su negocio.</h2><p>Le ayudamos a identificar qué necesita para comenzar con POS360.</p></div><a className="marketing-primary" href="https://wa.me/573124777829?text=Hola%2C%20quiero%20informaci%C3%B3n%20sobre%20POS360" target="_blank" rel="noreferrer">Hablar por WhatsApp</a></section>
<footer><Link className="marketing-brand" href="/"><span>P</span><div><b>POS360</b><small>Gestión comercial</small></div></Link><p>Software de gestión comercial para negocios colombianos.</p><nav><a href="#funciones">Funciones</a><a href="#precio">Precio</a><a href="#preguntas">Preguntas</a><a href="mailto:imagenplusamd@gmail.com">Soporte</a></nav><small>© 2026 POS360 · Imagen Plus. Todos los derechos reservados.</small></footer>
</main>}
function Heading({tag,title,copy}:{tag:string;title:string;copy?:string}){return <div className="section-heading"><span>{tag}</span><h2>{title}</h2>{copy&&<p>{copy}</p>}</div>}
function Download({icon,title,copy}:{icon:string;title:string;copy:string}){return <article><i>{icon}</i><div><h3>{title}</h3><p>{copy}</p></div><button disabled>Próximamente · versión firmada</button></article>}
