"use client";
import { useEffect, useState } from "react";
import { readJson } from "./api-client";

const money=(n:number)=>new Intl.NumberFormat("es-CO",{style:"currency",currency:"COP",maximumFractionDigits:2}).format(n||0);
type Order={id:string;number:string;supplierName:string;supplierId:string;status:string;total:number;balance:number;dueDate:string;receiptCount:number;receivedUnits:number;orderedUnits:number;createdAt:string};
type Supplier={id:string;name:string;documentNumber:string;contactName?:string;phone?:string;email?:string;paymentDays:number;balance:number;active:number};
type Product={id:string;name:string;sku:string;cost:number;stock:number;trackInventory:number};
type Warehouse={id:string;name:string;active:number};
type Modal="supplier"|"order"|"receive"|"pay"|"return"|"detail"|null;
const labels:Record<string,string>={draft:"Borrador",approved:"Autorizada",partial:"Recepción parcial",received:"Recibida"};

export default function Purchases({notify}:{notify:(s:string)=>void}){
  const [orders,setOrders]=useState<Order[]>([]),[suppliers,setSuppliers]=useState<Supplier[]>([]),[products,setProducts]=useState<Product[]>([]),[warehouses,setWarehouses]=useState<Warehouse[]>([]),[reports,setReports]=useState<any>({summary:{},aging:[],returns:[],credits:[]}),[modal,setModal]=useState<Modal>(null),[selected,setSelected]=useState<Order|null>(null),[detail,setDetail]=useState<any>(null),[supplier,setSupplier]=useState({documentNumber:"",name:"",contactName:"",phone:"",email:"",paymentDays:"30"}),[order,setOrder]=useState({supplierId:"",warehouseId:"",notes:"",lines:[{productId:"",quantity:"1",unitCost:"0"}]}),[receivePercent,setReceivePercent]=useState("100"),[payment,setPayment]=useState({amount:"",method:"transfer",paymentReference:""}),[returnForm,setReturnForm]=useState({productId:"",quantity:"1",reason:""});
  const load=async()=>{await fetch("/api/bootstrap");const [o,s,p,w,r]=await Promise.all([fetch("/api/purchases"),fetch("/api/suppliers"),fetch("/api/products"),fetch("/api/inventory-advanced"),fetch("/api/purchase-reports")]),[od,sd,pd,wd,rd]=await Promise.all([readJson<any>(o),readJson<any>(s),readJson<any>(p),readJson<any>(w),readJson<any>(r)]);setOrders(od.orders||[]);setSuppliers(sd.suppliers||[]);setProducts((pd.products||[]).filter((x:Product)=>x.trackInventory));setWarehouses((wd.warehouses||[]).filter((x:Warehouse)=>x.active));setReports(rd)};
  useEffect(()=>{load()},[]);
  const post=async(url:string,method:string,body:any)=>{const r=await fetch(url,{method,headers:{"content-type":"application/json"},body:JSON.stringify(body)}),d=await readJson<any>(r);if(!r.ok){notify(d.error);return null}return d};
  const saveSupplier=async()=>{const d=await post("/api/suppliers","POST",{...supplier,paymentDays:Number(supplier.paymentDays)});if(d){setModal(null);notify("Proveedor creado correctamente");load()}};
  const saveOrder=async()=>{const d=await post("/api/purchases","POST",{supplierId:order.supplierId,warehouseId:order.warehouseId,notes:order.notes,lines:order.lines.map(x=>({productId:x.productId,quantity:Number(x.quantity),unitCost:x.unitCost}))});if(d){setModal(null);notify(`Orden ${d.order.number} creada como borrador`);load()}};
  const action=async(action:string,extra:any={},target:Order|null=selected)=>{if(!target)return;const d=await post("/api/purchases","PATCH",{action,orderId:target.id,...extra});if(d){setModal(null);notify(action==="approve"?"Orden autorizada":action==="receive"?`Recepción ${d.reference} registrada completamente`:action==="pay"?`Pago registrado. Saldo ${money(d.remaining)}`:`Devolución ${d.reference} procesada`);load()}};
  const openDetail=async(o:Order)=>{setSelected(o);const r=await fetch(`/api/purchases?orderId=${o.id}`),d=await readJson<any>(r);setDetail(d);setModal("detail")};
  const addLine=()=>setOrder({...order,lines:[...order.lines,{productId:"",quantity:"1",unitCost:"0"}]});
  const changeLine=(i:number,key:string,value:string)=>{const lines=order.lines.map((x,n)=>n===i?{...x,[key]:value}:x);if(key==="productId"){const p=products.find(x=>x.id===value);lines[i].unitCost=String(p?.cost||0)}setOrder({...order,lines})};
  const summary=reports.summary||{};
  return <>
    <div className="page-intro"><div><h2>Proveedores y compras</h2><p>Ciclo controlado: orden, autorización, recepción, cuenta por pagar, pago y devolución.</p></div><div><button className="secondary" onClick={()=>setModal("supplier")}>+ Proveedor</button><button className="primary" onClick={()=>{setOrder({supplierId:suppliers[0]?.id||"",warehouseId:warehouses[0]?.id||"",notes:"",lines:[{productId:products[0]?.id||"",quantity:"1",unitCost:String(products[0]?.cost||0)}]});setModal("order")}}>+ Orden de compra</button></div></div>
    <div className="summary-strip"><K label="Proveedores" value={String(suppliers.length)} tone="blue"/><K label="Órdenes por autorizar" value={String(orders.filter(x=>x.status==="draft").length)} tone="orange"/><K label="Saldo por pagar" value={money(summary.payable)} tone="purple"/><K label="Cartera vencida" value={money(summary.overdue)} tone="green"/></div>
    <article className="panel table-panel"><div className="filters"><b>Órdenes de compra</b><span className="db-badge">● Recepción atómica y kardex conectado</span></div><table><thead><tr><th>Orden</th><th>Proveedor</th><th>Avance</th><th>Total / saldo</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{orders.length?orders.map(o=><tr key={o.id}><td><button className="table-action" onClick={()=>openDetail(o)}><b>{o.number}</b></button><small className="cell-sub">{new Date(o.createdAt).toLocaleDateString("es-CO")}</small></td><td>{o.supplierName}</td><td>{o.receivedUnits||0} / {o.orderedUnits||0} und.<small className="cell-sub">{o.receiptCount} recepción(es)</small></td><td>{money(o.total)}<small className={o.balance?"cell-sub debt":"cell-sub"}>Saldo {money(o.balance)}</small></td><td><span className={o.status==="received"?"status ok":"status low"}>{labels[o.status]||o.status}</span></td><td><div className="row-actions">{o.status==="draft"&&<button className="table-action" onClick={()=>action("approve",{},o)}>Autorizar</button>}{["approved","partial"].includes(o.status)&&<button className="table-action" onClick={()=>{setSelected(o);setReceivePercent("100");setModal("receive")}}>Recibir</button>}{o.balance>0&&<button className="table-action" onClick={()=>{setSelected(o);setPayment({amount:String(o.balance),method:"transfer",paymentReference:""});setModal("pay")}}>Pagar</button>}{o.receiptCount>0&&<button className="table-action danger" onClick={()=>{setSelected(o);setReturnForm({productId:products[0]?.id||"",quantity:"1",reason:""});setModal("return")}}>Devolver</button>}</div></td></tr>):<tr><td colSpan={6}>Cree el proveedor y la primera orden de compra.</td></tr>}</tbody></table></article>
    <div className="purchase-dashboard"><article className="panel table-panel"><div className="filters"><b>Directorio de proveedores</b></div><table><thead><tr><th>Proveedor</th><th>NIT/documento</th><th>Contacto</th><th>Plazo</th><th>Saldo</th></tr></thead><tbody>{suppliers.map(s=><tr key={s.id}><td><b>{s.name}</b></td><td>{s.documentNumber}</td><td>{s.contactName||"—"}<small className="cell-sub">{s.phone||s.email||"Sin contacto"}</small></td><td>{s.paymentDays} días</td><td className={s.balance?"debt":""}>{money(s.balance)}</td></tr>)}</tbody></table></article><aside className="panel"><div className="panel-head"><div><h3>Vencimientos</h3><p>Prioridad de pago por proveedor</p></div></div>{(reports.aging||[]).map((a:any)=><div className="supplier-aging" key={a.supplier}><div><b>{a.supplier}</b><small>Próximo: {a.nextDue}</small></div><strong>{money(a.balance)}</strong>{a.overdue>0&&<span>Vencido {money(a.overdue)}</span>}</div>)}{!(reports.aging||[]).length&&<div className="success-box">No hay cuentas pendientes.</div>}</aside></div>
    <article className="panel table-panel returns-panel"><div className="filters"><b>Devoluciones y notas crédito</b></div><table><thead><tr><th>Referencia</th><th>Proveedor</th><th>Motivo</th><th>Fecha</th><th>Valor</th></tr></thead><tbody>{(reports.returns||[]).map((x:any)=><tr key={x.reference}><td><b>{x.reference}</b></td><td>{x.supplier}</td><td>{x.reason}</td><td>{new Date(x.createdAt).toLocaleDateString("es-CO")}</td><td>{money(x.total)}</td></tr>)}</tbody></table></article>
    {modal&&<div className="modal-backdrop" onMouseDown={()=>setModal(null)}><section className="modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><h3>{modal==="supplier"?"Nuevo proveedor":modal==="order"?"Nueva orden de compra":modal==="receive"?"Recepción de mercancía":modal==="pay"?"Pago a proveedor":modal==="return"?"Devolución al proveedor":"Trazabilidad de la orden"}</h3><p>{selected?.number||"Ciclo de compras POS360"}</p></div><button onClick={()=>setModal(null)}>×</button></div>
      {modal==="supplier"?<div className="form-grid">{[["documentNumber","NIT o documento"],["name","Nombre o razón social"],["contactName","Persona de contacto"],["phone","Teléfono"],["email","Correo"],["paymentDays","Plazo de pago en días"]].map(([key,label])=><label key={key}>{label}<input type={key==="paymentDays"?"number":"text"} value={(supplier as any)[key]} onChange={e=>setSupplier({...supplier,[key]:e.target.value})}/></label>)}</div>
      :modal==="order"?<div className="payment-body"><div className="form-grid"><label>Proveedor<select value={order.supplierId} onChange={e=>setOrder({...order,supplierId:e.target.value})}><option value="">Seleccione</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Bodega de recepción<select value={order.warehouseId} onChange={e=>setOrder({...order,warehouseId:e.target.value})}><option value="">Seleccione</option>{warehouses.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label></div>{order.lines.map((line,i)=><div className="form-grid" key={i}><label>Producto<select value={line.productId} onChange={e=>changeLine(i,"productId",e.target.value)}><option value="">Seleccione</option>{products.map(p=><option key={p.id} value={p.id}>{p.name} · {p.sku}</option>)}</select></label><label>Cantidad<input type="number" min="0.01" step="0.01" value={line.quantity} onChange={e=>changeLine(i,"quantity",e.target.value)}/></label><label>Costo unitario<input type="number" min="0" step="0.01" value={line.unitCost} onChange={e=>changeLine(i,"unitCost",e.target.value)}/></label>{order.lines.length>1&&<button className="secondary" onClick={()=>setOrder({...order,lines:order.lines.filter((_,n)=>n!==i)})}>Quitar</button>}</div>)}<button className="secondary" onClick={addLine}>+ Agregar producto</button><label>Observaciones<textarea value={order.notes} onChange={e=>setOrder({...order,notes:e.target.value})}/></label><div className="success-box">La orden se guardará como borrador y deberá autorizarse antes de recibir.</div></div>
      :modal==="receive"?<div className="payment-body"><label>Porcentaje de cada cantidad pendiente<select value={receivePercent} onChange={e=>setReceivePercent(e.target.value)}><option value="25">25%</option><option value="50">50%</option><option value="75">75%</option><option value="100">100%</option></select></label><div className="success-box">Inventario, kardex, costos, recepción y cuenta por pagar se guardarán juntos. Si una operación falla, no se registra ninguna.</div></div>
      :modal==="pay"?<div className="payment-body"><div className="receipt-total"><span>Saldo pendiente</span><b>{money(selected?.balance||0)}</b></div><label>Valor<input type="number" min="0.01" step="0.01" value={payment.amount} onChange={e=>setPayment({...payment,amount:e.target.value})}/></label><label>Medio<select value={payment.method} onChange={e=>setPayment({...payment,method:e.target.value})}><option value="transfer">Transferencia</option><option value="cash">Efectivo</option><option value="card">Tarjeta</option><option value="check">Cheque</option></select></label><label>Referencia bancaria o comprobante<input value={payment.paymentReference} onChange={e=>setPayment({...payment,paymentReference:e.target.value})}/></label></div>
      :modal==="return"?<div className="payment-body"><label>Producto<select value={returnForm.productId} onChange={e=>setReturnForm({...returnForm,productId:e.target.value})}><option value="">Seleccione</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Cantidad<input type="number" min="0.01" step="0.01" value={returnForm.quantity} onChange={e=>setReturnForm({...returnForm,quantity:e.target.value})}/></label><label>Motivo obligatorio<input value={returnForm.reason} onChange={e=>setReturnForm({...returnForm,reason:e.target.value})}/></label></div>
      :<div className="payment-body">{detail?.order&&<><div className="receipt-total"><span>{detail.order.supplierName}</span><b>{labels[detail.order.status]}</b></div><h4>Productos</h4>{(detail.lines||[]).map((l:any)=><div className="receipt-total" key={l.id}><span>{l.productName}<small className="cell-sub">Pedido {l.quantity} · recibido {l.receivedQuantity} · devuelto {l.returnedQuantity}</small></span><b>{money(l.lineTotalMinor/100)}</b></div>)}<h4>Historial</h4>{(detail.events||[]).map((e:any)=><div className="supplier-aging" key={e.id}><div><b>{e.action} · {e.userName}</b><small>{new Date(e.createdAt).toLocaleString("es-CO")} · {e.reason}</small></div><span>{e.reference||e.toStatus}</span></div>)}</>}</div>}
      {modal!=="detail"&&<div className="modal-actions"><button className="secondary" onClick={()=>setModal(null)}>Cancelar</button><button className="primary" onClick={()=>modal==="supplier"?saveSupplier():modal==="order"?saveOrder():modal==="receive"?action("receive",{percent:Number(receivePercent)}):modal==="pay"?action("pay",payment):action("return",{...returnForm,quantity:Number(returnForm.quantity)})}>{modal==="supplier"?"Guardar proveedor":modal==="order"?"Crear borrador":modal==="receive"?"Confirmar recepción":modal==="pay"?"Registrar pago":"Procesar devolución"}</button></div>}</section></div>}
  </>;
}
function K({label,value,tone}:{label:string;value:string;tone:string}){return <div className="kpi"><div className={`kpi-icon ${tone}`}>$</div><div><span>{label}</span><strong>{value}</strong><small>Control de compras</small></div></div>}
