import {Device} from "@capacitor/device";import {Network} from "@capacitor/network";import {Preferences} from "@capacitor/preferences";import "./style.css";
const root=document.querySelector("#app"),state={data:null,tab:"inventory",online:true,cart:[],message:"",token:"",api:""};
const stored=async key=>JSON.parse((await Preferences.get({key})).value||"null"),save=(key,value)=>Preferences.set({key,value:JSON.stringify(value)});
async function init(){const config=await stored("config");state.token=config?.token||"";state.api=config?.api||"";state.data=await stored("snapshot");state.online=(await Network.getStatus()).connected;Network.addListener("networkStatusChange",async status=>{state.online=status.connected;render();if(status.connected)await flush()});render();if(state.token&&state.api)await sync()}
async function request(path,options={}){const response=await fetch(`${state.api}${path}`,{...options,headers:{"content-type":"application/json","authorization":`Bearer ${state.token}`,...options.headers}}),text=await response.text(),data=text?JSON.parse(text):{};if(!response.ok)throw new Error(data.error||`Error ${response.status}`);return data}
async function sync(){try{const data=await request("/api/mobile");state.data=data;await save("snapshot",data);state.message=`Sincronizado ${new Date().toLocaleTimeString("es-CO")}`;await flush()}catch(error){state.message=`Modo local: ${error.message}`}render()}
async function enqueue(action,payload){const queue=await stored("queue")||[],operation={...payload,action,operationId:crypto.randomUUID(),createdAt:new Date().toISOString()};queue.push(operation);await save("queue",queue);state.message="Operación guardada en el dispositivo";render();if(state.online)await flush()}
async function flush(){if(!state.token||!state.api)return;const queue=await stored("queue")||[],pending=[];for(const operation of queue)try{await request("/api/mobile",{method:"POST",body:JSON.stringify(operation)})}catch(error){pending.push(operation);state.message=`Pendiente: ${error.message}`}await save("queue",pending);if(!pending.length&&queue.length){state.message=`${queue.length} operación(es) sincronizada(s)`;await sync()}render()}
const money=minor=>new Intl.NumberFormat("es-CO",{style:"currency",currency:"COP",maximumFractionDigits:0}).format((minor||0)/100),esc=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
function shell(content){const session=state.data?.session;return `<header><div class="logo">P</div><div><b>POS360 Móvil</b><small>${esc(session?`${session.company} · ${session.branch}`:"Configuración inicial")}</small></div><span class="net ${state.online?"on":"off"}">${state.online?"En línea":"Sin conexión"}</span></header>${state.message?`<div class="message">${esc(state.message)}</div>`:""}<main>${content}</main>${session?`<nav>${[["inventory","Inventario","▦"],["purchases","Compras","↓"],["orders","Pedidos","▣"],["alerts","Alertas","!"]].map(([id,label,icon])=>`<button data-tab="${id}" class="${state.tab===id?"active":""}"><i>${icon}</i>${label}</button>`).join("")}</nav>`:""}`}
function render(){if(!state.token||!state.api){root.innerHTML=shell(`<section class="card setup"><h1>Conectar dispositivo</h1><p>Ingrese la dirección segura de POS360 y el token entregado por el administrador.</p><label>Servidor<input id="api" placeholder="https://pos360.example.com" value="${esc(state.api)}"></label><label>Token del dispositivo<input id="token" type="password" value="${esc(state.token)}"></label><button id="connect" class="primary">Conectar y descargar datos</button></section>`);bindSetup();return}const views={inventory:inventoryView,purchases:purchasesView,orders:ordersView,alerts:alertsView};root.innerHTML=shell((views[state.tab]||inventoryView)());bind()}
function inventoryView(){const products=state.data?.products||[];return `<div class="title"><div><h1>Inventario</h1><p>${products.length} productos disponibles localmente</p></div><button id="sync">↻</button></div><input id="search" class="search" placeholder="Buscar nombre, SKU o código"><section id="product-list">${products.map(productCard).join("")}</section>`}
const productCard=p=>`<article class="card product" data-search="${esc(`${p.name} ${p.sku} ${p.barcode||""}`.toLowerCase())}"><div><b>${esc(p.name)}</b><small>${esc(p.sku)} · ${esc(p.category)}</small></div><strong class="${p.stock<=0?"danger":p.stock<5?"warning":""}">${p.stock}</strong><span>${money(p.priceMinor)}</span></article>`;
function purchasesView(){const orders=state.data?.purchaseOrders||[],lines=state.data?.purchaseLines||[];return `<div class="title"><div><h1>Recepción de compras</h1><p>Recepciones parciales o totales con trazabilidad</p></div></div>${orders.map(order=>`<article class="card purchase"><b>${esc(order.number)} · ${esc(order.supplierName)}</b><small>${order.pendingUnits} unidades pendientes</small>${lines.filter(line=>line.orderId===order.id).map(line=>`<label class="receive-line"><span>${esc(line.productName)}<small>Pendiente ${line.pendingQuantity}</small></span><input type="number" min="0" max="${line.pendingQuantity}" step="any" value="${line.pendingQuantity}" data-line="${line.lineId}"></label>`).join("")}<button class="primary receive" data-order="${order.id}">Registrar recepción</button></article>`).join("")||`<div class="empty">No hay órdenes autorizadas pendientes.</div>`}`}
function ordersView(){const products=state.data?.products||[],orders=state.data?.mobileOrders||[];return `<div class="title"><div><h1>Pedidos</h1><p>Se guardan localmente antes de sincronizar</p></div></div><section class="card order-form"><label>Producto<select id="order-product"><option value="">Seleccione…</option>${products.map(p=>`<option value="${p.id}">${esc(p.name)} · ${money(p.priceMinor)}</option>`).join("")}</select></label><label>Cantidad<input id="order-qty" type="number" min="0.001" step="any" value="1"></label><button id="add-order" class="primary">Agregar al pedido</button><div class="cart">${state.cart.map((x,i)=>`<div><span>${esc(products.find(p=>p.id===x.productId)?.name)} × ${x.quantity}</span><button data-remove="${i}">×</button></div>`).join("")}</div><label>Observaciones<input id="order-notes"></label><button id="save-order" class="primary" ${state.cart.length?"":"disabled"}>Guardar pedido</button></section><h2>Pedidos recientes</h2>${orders.map(o=>`<article class="card row"><div><b>${o.number}</b><small>${esc(o.customerName)} · ${o.status}</small></div><strong>${money(o.totalMinor)}</strong></article>`).join("")}`}
function alertsView(){const alerts=state.data?.alerts||[];return `<div class="title"><div><h1>Alertas</h1><p>Inventario, compras y operación</p></div></div>${alerts.map(a=>`<article class="card alert ${a.severity}"><div><b>${esc(a.title)}</b><p>${esc(a.message)}</p><small>${new Date(a.createdAt).toLocaleString("es-CO")}</small></div><button data-alert="${a.id}">Atendida</button></article>`).join("")||`<div class="empty">No hay alertas abiertas.</div>`}`}
function bindSetup(){document.querySelector("#connect")?.addEventListener("click",async()=>{state.api=document.querySelector("#api").value.replace(/\/$/,"");state.token=document.querySelector("#token").value;await save("config",{api:state.api,token:state.token});await sync()})}
function bind(){document.querySelectorAll("[data-tab]").forEach(button=>button.addEventListener("click",()=>{state.tab=button.dataset.tab;render()}));document.querySelector("#sync")?.addEventListener("click",sync);document.querySelector("#search")?.addEventListener("input",event=>document.querySelectorAll("[data-search]").forEach(card=>card.hidden=!card.dataset.search.includes(event.target.value.toLowerCase())));document.querySelectorAll(".receive").forEach(button=>button.addEventListener("click",()=>{const lines=[...button.closest("article").querySelectorAll("[data-line]")].map(input=>({lineId:input.dataset.line,quantity:Number(input.value)})).filter(x=>x.quantity>0);enqueue("receive_purchase",{orderId:button.dataset.order,lines,reason:"Recepción verificada desde Android"})}));document.querySelector("#add-order")?.addEventListener("click",()=>{const productId=document.querySelector("#order-product").value,quantity=Number(document.querySelector("#order-qty").value);if(productId&&quantity>0){state.cart.push({productId,quantity});render()}});document.querySelectorAll("[data-remove]").forEach(button=>button.addEventListener("click",()=>{state.cart.splice(Number(button.dataset.remove),1);render()}));document.querySelector("#save-order")?.addEventListener("click",()=>{enqueue("order",{lines:state.cart,notes:document.querySelector("#order-notes").value});state.cart=[]});document.querySelectorAll("[data-alert]").forEach(button=>button.addEventListener("click",()=>enqueue("ack_alert",{alertId:button.dataset.alert})));Device.getInfo().then(info=>enqueue("telemetry",{eventType:"app.screen",level:"info",appVersion:"1.0.0",payload:{tab:state.tab,platform:info.platform,osVersion:info.osVersion}}))}
init();
