export async function processElectronicBillingQueue(db:D1Database,limit=25){
  const pending=await db.prepare("SELECT x.id,x.tenant_id tenantId,x.number,x.total_minor totalMinor,x.issue_date issueDate,x.retry_count retryCount,p.provider_type providerType,p.endpoint,p.credential_reference credentialReference FROM electronic_documents x JOIN electronic_billing_providers p ON p.id=x.provider_id WHERE x.status='queued' AND (x.next_retry_at IS NULL OR x.next_retry_at<=CURRENT_TIMESTAMP) ORDER BY x.created_at LIMIT ?").bind(limit).all<{id:string;tenantId:string;number:string;totalMinor:number;issueDate:string;retryCount:number;providerType:string;endpoint:string|null;credentialReference:string|null}>(),results=[];
  for(const document of pending.results){
    const attempt=document.retryCount+1,accepted=document.providerType==="sandbox",code=accepted?"00":document.endpoint&&document.credentialReference?"ADAPTER_REQUIRED":"PROVIDER_CONFIG",message=accepted?"Aceptado automáticamente en simulador de habilitación POS360":code==="ADAPTER_REQUIRED"?"El adaptador certificado debe procesar el documento":"Proveedor incompleto",next=accepted?"accepted":attempt>=5?"rejected":"queued",cufe=accepted?await sha(`${document.number}|${document.totalMinor}|${document.issueDate}`):null,nextRetry=next==="queued"?new Date(Date.now()+Math.min(3600,30*2**attempt)*1000).toISOString().replace("T"," ").slice(0,19):null,attemptId=crypto.randomUUID(),response=JSON.stringify({code,message,accepted,automatic:true});
    await db.batch([db.prepare("INSERT INTO electronic_document_attempts(id,tenant_id,document_id,attempt_number,request_payload,response_payload,http_status,result,error_code,error_message,completed_at) VALUES(?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP)").bind(attemptId,document.tenantId,document.id,attempt,JSON.stringify({number:document.number,automatic:true}),response,accepted?200:503,accepted?"accepted":"temporary_error",accepted?null:code,accepted?null:message),db.prepare("UPDATE electronic_documents SET status=?,cufe=COALESCE(?,cufe),provider_status_code=?,provider_message=?,retry_count=?,next_retry_at=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND status='queued'").bind(next,cufe,code,message,attempt,nextRetry,document.id),db.prepare("INSERT INTO electronic_document_events(id,tenant_id,document_id,event_type,from_status,to_status,details) VALUES(?,?,?,'automatic_retry','queued',?,?)").bind(crypto.randomUUID(),document.tenantId,document.id,next,response)]);results.push({id:document.id,status:next})
  }
  return results;
}
const sha=async(value:string)=>Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value)))).map(x=>x.toString(16).padStart(2,"0")).join("");
