import { DatabaseSync } from "node:sqlite";
import { randomUUID } from "node:crypto";
export class LocalPOSDatabase{
  constructor(path){this.path=path;this.db=new DatabaseSync(path);this.db.exec("PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON; PRAGMA synchronous=FULL; PRAGMA busy_timeout=5000;");this.migrate();this.recover()}
  migrate(){this.db.exec(`CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL);CREATE TABLE IF NOT EXISTS catalog(id TEXT PRIMARY KEY,sku TEXT NOT NULL,name TEXT NOT NULL,price_minor INTEGER NOT NULL,cost_minor INTEGER NOT NULL,stock REAL NOT NULL,track_inventory INTEGER NOT NULL,version INTEGER NOT NULL,barcodes TEXT NOT NULL DEFAULT '[]');CREATE TABLE IF NOT EXISTS local_sales(id TEXT PRIMARY KEY,operation_id TEXT UNIQUE NOT NULL,total_minor INTEGER NOT NULL,status TEXT NOT NULL,customer_id TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS local_sale_lines(id TEXT PRIMARY KEY,sale_id TEXT NOT NULL REFERENCES local_sales(id),product_id TEXT NOT NULL,quantity REAL NOT NULL,unit_price_minor INTEGER NOT NULL,line_total_minor INTEGER NOT NULL);CREATE TABLE IF NOT EXISTS local_payments(id TEXT PRIMARY KEY,sale_id TEXT NOT NULL REFERENCES local_sales(id),method TEXT NOT NULL,amount_minor INTEGER NOT NULL,reference TEXT);CREATE UNIQUE INDEX IF NOT EXISTS local_payment_method_uq ON local_payments(sale_id,method);CREATE TABLE IF NOT EXISTS outbox(id TEXT PRIMARY KEY,operation_id TEXT UNIQUE NOT NULL,type TEXT NOT NULL,payload TEXT NOT NULL,status TEXT DEFAULT 'pending' NOT NULL,attempts INTEGER DEFAULT 0 NOT NULL,last_error TEXT,next_attempt_at TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS conflicts(id TEXT PRIMARY KEY,operation_id TEXT UNIQUE NOT NULL,error TEXT NOT NULL,payload TEXT NOT NULL,status TEXT DEFAULT 'pending' NOT NULL,resolution TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,resolved_at TEXT);CREATE TABLE IF NOT EXISTS print_jobs(id TEXT PRIMARY KEY,sale_id TEXT NOT NULL,kind TEXT NOT NULL,payload BLOB NOT NULL,status TEXT DEFAULT 'pending' NOT NULL,attempts INTEGER DEFAULT 0 NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP);`)}
  recover(){this.db.exec("UPDATE outbox SET status='pending',last_error='Recuperado después de cierre inesperado' WHERE status='processing';UPDATE print_jobs SET status='pending' WHERE status='printing';");const check=this.db.prepare("PRAGMA integrity_check").get();if(check.integrity_check!=="ok")throw new Error(`SQLite corrupto: ${check.integrity_check}`)}
  setting(key,value){if(value===undefined){const row=this.db.prepare("SELECT value FROM settings WHERE key=?").get(key);return row?JSON.parse(row.value):null}this.db.prepare("INSERT INTO settings(key,value) VALUES (?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").run(key,JSON.stringify(value));return value}
  importCatalog(snapshot){this.db.exec("BEGIN IMMEDIATE");try{const up=this.db.prepare("INSERT INTO catalog(id,sku,name,price_minor,cost_minor,stock,track_inventory,version,barcodes) VALUES (?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET sku=excluded.sku,name=excluded.name,price_minor=excluded.price_minor,cost_minor=excluded.cost_minor,stock=CASE WHEN catalog.version<=excluded.version THEN excluded.stock ELSE catalog.stock END,track_inventory=excluded.track_inventory,version=MAX(catalog.version,excluded.version),barcodes=excluded.barcodes");for(const p of snapshot.products)up.run(p.id,p.sku,p.name,p.priceMinor,p.costMinor,p.stock,Number(p.trackInventory),p.version,JSON.stringify([p.barcode,...(p.barcodes||[])].filter(Boolean)));this.setting("terminal",snapshot.terminal);this.setting("business",snapshot.settings);this.setting("catalogVersion",snapshot.catalogVersion);this.db.exec("COMMIT")}catch(e){this.db.exec("ROLLBACK");throw e}}
  findProduct(code){return this.db.prepare("SELECT * FROM catalog WHERE id=? OR sku=? OR EXISTS(SELECT 1 FROM json_each(catalog.barcodes) WHERE value=?) LIMIT 1").get(code,code,code)}
  createSale(input){const operationId=input.operationId||`${this.setting("terminal")?.id||"terminal"}-${randomUUID()}`,existing=this.db.prepare("SELECT id,total_minor totalMinor,status FROM local_sales WHERE operation_id=?").get(operationId);if(existing)return{...existing,operationId,duplicate:true};this.db.exec("BEGIN IMMEDIATE");try{let total=0;const lines=[];for(const item of input.items){const p=this.db.prepare("SELECT * FROM catalog WHERE id=?").get(item.productId);if(!p||!Number.isFinite(item.quantity)||item.quantity<=0)throw new Error("Producto o cantidad local inválida");if(p.track_inventory&&p.stock<item.quantity)throw new Error(`Stock local insuficiente: ${p.name}`);const line=Math.round(p.price_minor*item.quantity);total+=line;lines.push({p,item,line})}const discount=Math.round(total*Math.max(0,Math.min(100,input.discountPercent||0))/100);total-=discount;const grouped=new Map;for(const payment of input.payments){const amount=Math.round(Number(payment.amountMinor));grouped.set(payment.method,(grouped.get(payment.method)||0)+amount)}if([...grouped.values()].reduce((a,b)=>a+b,0)!==total)throw new Error("Los pagos locales no coinciden con el total");const saleId=randomUUID();this.db.prepare("INSERT INTO local_sales(id,operation_id,total_minor,status,customer_id) VALUES (?,?,?,'pending_sync',?)").run(saleId,operationId,total,input.customerId||null);for(const {p,item,line} of lines){this.db.prepare("INSERT INTO local_sale_lines(id,sale_id,product_id,quantity,unit_price_minor,line_total_minor) VALUES (?,?,?,?,?,?)").run(randomUUID(),saleId,p.id,item.quantity,p.price_minor,line);if(p.track_inventory)this.db.prepare("UPDATE catalog SET stock=stock-?,version=version+1 WHERE id=?").run(item.quantity,p.id)}for(const [method,amount] of grouped)this.db.prepare("INSERT INTO local_payments(id,sale_id,method,amount_minor,reference) VALUES (?,?,?,?,?)").run(randomUUID(),saleId,method,amount,input.references?.[method]||null);const payload={localId:operationId,customerId:input.customerId,items:input.items,payments:[...grouped].map(([method,amountMinor])=>({method,amount:amountMinor/100})),discountPercent:input.discountPercent||0,discountReason:input.discountReason};this.db.prepare("INSERT INTO outbox(id,operation_id,type,payload) VALUES (?,?, 'sale',?)").run(randomUUID(),operationId,JSON.stringify(payload));this.db.prepare("INSERT INTO print_jobs(id,sale_id,kind,payload) VALUES (?,?, 'receipt',?)").run(randomUUID(),saleId,receiptBytes({saleId,operationId,total,lines:lines.map(x=>({name:x.p.name,quantity:x.item.quantity,total:x.line}))}));this.db.exec("COMMIT");return{id:saleId,operationId,totalMinor:total,status:"pending_sync"}}catch(e){this.db.exec("ROLLBACK");throw e}}
  pending(limit=50){return this.db.prepare("SELECT * FROM outbox WHERE status='pending' AND (next_attempt_at IS NULL OR next_attempt_at<=CURRENT_TIMESTAMP) ORDER BY created_at LIMIT ?").all(limit)}
  markProcessing(ids){const q=this.db.prepare("UPDATE outbox SET status='processing',attempts=attempts+1,updated_at=CURRENT_TIMESTAMP WHERE id=? AND status='pending'");for(const id of ids)q.run(id)}
  acknowledge(result){const row=this.db.prepare("SELECT payload FROM outbox WHERE operation_id=?").get(result.id);if(!row)return;if(result.status==="applied"){this.db.prepare("UPDATE outbox SET status='applied',last_error=NULL,updated_at=CURRENT_TIMESTAMP WHERE operation_id=?").run(result.id);this.db.prepare("UPDATE local_sales SET status='synced' WHERE operation_id=?").run(result.id)}else{this.db.prepare("UPDATE outbox SET status='conflict',last_error=?,updated_at=CURRENT_TIMESTAMP WHERE operation_id=?").run(result.error||"Conflicto",result.id);this.db.prepare("INSERT INTO conflicts(id,operation_id,error,payload) VALUES (?,?,?,?) ON CONFLICT(operation_id) DO NOTHING").run(randomUUID(),result.id,result.error||"Conflicto",row.payload)}}
  retry(ids,error){const q=this.db.prepare("UPDATE outbox SET status='pending',last_error=?,next_attempt_at=datetime('now','+'||(MIN(attempts,6)*5)||' seconds'),updated_at=CURRENT_TIMESTAMP WHERE id=?");for(const id of ids)q.run(error,id)}
  stats(){return{sales:this.db.prepare("SELECT COUNT(*) count FROM local_sales").get().count,pending:this.db.prepare("SELECT COUNT(*) count FROM outbox WHERE status='pending'").get().count,conflicts:this.db.prepare("SELECT COUNT(*) count FROM conflicts WHERE status='pending'").get().count,integrity:this.db.prepare("PRAGMA integrity_check").get().integrity_check}}
  nextPrint(){return this.db.prepare("SELECT * FROM print_jobs WHERE status='pending' ORDER BY created_at LIMIT 1").get()}
  markPrinted(id,ok){this.db.prepare(`UPDATE print_jobs SET status=?,attempts=attempts+1 WHERE id=?`).run(ok?"printed":"pending",id)}
  close(){this.db.close()}
}
export function receiptBytes({operationId,total,lines}){const esc="\x1b",text=[`${esc}@`,`${esc}a\x01POS360\n`,`${esc}a\x00Operación ${operationId}\n`,...lines.map(x=>`${x.quantity} x ${x.name}  $${(x.total/100).toFixed(2)}\n`),"--------------------------------\n",`TOTAL $${(total/100).toFixed(2)}\n\n\n`,`${esc}p\x00\x19\xfa`,"\x1dV\x00"].join("");return Buffer.from(text,"binary")}
