import {randomUUID} from "node:crypto";
import {getRuntimeEnv} from "../../../db/runtime-env";
import {requestIdentityEmail} from "../../../db/request-identity";

async function authorize(req:Request,write=false){const email=requestIdentityEmail(req);if(!email)return {error:Response.json({error:"Autenticación requerida"},{status:401})};const admin=await getRuntimeEnv().DB.prepare("SELECT id,email,display_name displayName,role FROM platform_admins WHERE email=? AND active=1").bind(email).first<{id:string;email:string;displayName:string;role:string}>();if(!admin)return {error:Response.json({error:"Acceso exclusivo para el equipo propietario de POS360"},{status:403})};if(write&&admin.role==="platform_auditor")return {error:Response.json({error:"El auditor de plataforma tiene acceso de solo lectura"},{status:403})};return {admin}}
const audit=(req:Request,adminId:string,tenantId:string|null,action:string,entityType:string,entityId:string,reason:string,metadata:unknown={})=>getRuntimeEnv().DB.prepare("INSERT INTO platform_audit_logs(id,platform_admin_id,tenant_id,action,entity_type,entity_id,reason,metadata,ip_address) VALUES(?,?,?,?,?,?,?,?,?)").bind(randomUUID(),adminId,tenantId,action,entityType,entityId,reason,JSON.stringify(metadata),req.headers.get("x-forwarded-for")||null);

export async function GET(req:Request){
  const auth=await authorize(req);if(auth.error)return auth.error;const d=getRuntimeEnv().DB,url=new URL(req.url),tenantId=url.searchParams.get("tenantId");
  const [summary,companies,plans,tickets,terminals,audits,accessGrants,syncHealth]=await Promise.all([
    d.prepare("SELECT COUNT(*) companies,SUM(CASE WHEN status='active' THEN 1 ELSE 0 END) activeCompanies,SUM(CASE WHEN status='suspended' THEN 1 ELSE 0 END) suspendedCompanies,(SELECT COUNT(*) FROM terminals) terminals,(SELECT COUNT(*) FROM platform_support_tickets WHERE status NOT IN ('resolved','closed')) openTickets,(SELECT COUNT(*) FROM desktop_sync_operations WHERE status='conflict') syncConflicts FROM tenants").first(),
    d.prepare("SELECT t.id,t.name,t.country,t.status,COALESCE(bs.sector,'retail') sector,s.status subscriptionStatus,s.trial_ends_at trialEndsAt,s.current_period_end currentPeriodEnd,p.id planId,p.name planName,p.max_branches maxBranches,p.max_users maxUsers,p.max_terminals maxTerminals,p.max_products maxProducts,(SELECT COUNT(*) FROM branches b WHERE b.tenant_id=t.id) branches,(SELECT COUNT(*) FROM app_users u WHERE u.tenant_id=t.id AND u.active=1) users,(SELECT COUNT(*) FROM terminals x WHERE x.tenant_id=t.id) terminals,(SELECT COUNT(*) FROM products x WHERE x.tenant_id=t.id AND x.active=1) products,(SELECT MAX(created_at) FROM sync_events e WHERE e.tenant_id=t.id) lastSyncAt,(SELECT COUNT(*) FROM desktop_sync_operations o WHERE o.tenant_id=t.id AND o.status='conflict') syncConflicts FROM tenants t LEFT JOIN business_settings bs ON bs.tenant_id=t.id LEFT JOIN tenant_subscriptions s ON s.tenant_id=t.id LEFT JOIN saas_plans p ON p.id=s.plan_id ORDER BY t.created_at DESC").all(),
    d.prepare("SELECT id,code,name,price_minor priceMinor,billing_period billingPeriod,max_branches maxBranches,max_users maxUsers,max_terminals maxTerminals,max_products maxProducts,offline_enabled offlineEnabled,active,(SELECT COUNT(*) FROM tenant_subscriptions s WHERE s.plan_id=p.id AND s.status IN ('trial','active')) subscribers FROM saas_plans p ORDER BY price_minor").all(),
    d.prepare("SELECT x.id,x.number,x.tenant_id tenantId,t.name company,x.subject,x.description,x.priority,x.status,x.created_by_email createdByEmail,x.resolution,x.created_at createdAt,x.updated_at updatedAt,a.display_name assignedName FROM platform_support_tickets x JOIN tenants t ON t.id=x.tenant_id LEFT JOIN platform_admins a ON a.id=x.assigned_to WHERE (? IS NULL OR x.tenant_id=?) ORDER BY CASE x.priority WHEN 'critical' THEN 0 WHEN 'high' THEN 1 ELSE 2 END,x.created_at DESC LIMIT 100").bind(tenantId,tenantId).all(),
    d.prepare("SELECT x.id,x.tenant_id tenantId,t.name company,x.name,x.code,x.status,c.id deviceFingerprint,c.last_sync_at lastSyncAt,c.status credentialStatus,(SELECT COUNT(*) FROM desktop_sync_operations o WHERE o.terminal_id=x.id AND o.status='conflict') conflicts FROM terminals x JOIN tenants t ON t.id=x.tenant_id LEFT JOIN desktop_terminal_credentials c ON c.terminal_id=x.id WHERE (? IS NULL OR x.tenant_id=?) ORDER BY t.name,x.name").bind(tenantId,tenantId).all(),
    d.prepare("SELECT l.id,l.tenant_id tenantId,t.name company,a.display_name adminName,l.action,l.entity_type entityType,l.entity_id entityId,l.reason,l.metadata,l.ip_address ipAddress,l.created_at createdAt FROM platform_audit_logs l JOIN platform_admins a ON a.id=l.platform_admin_id LEFT JOIN tenants t ON t.id=l.tenant_id WHERE (? IS NULL OR l.tenant_id=?) ORDER BY l.created_at DESC LIMIT 100").bind(tenantId,tenantId).all(),
    d.prepare("SELECT g.id,g.tenant_id tenantId,t.name company,a.display_name adminName,g.reason,g.status,g.expires_at expiresAt,g.created_at createdAt FROM platform_access_grants g JOIN tenants t ON t.id=g.tenant_id JOIN platform_admins a ON a.id=g.platform_admin_id WHERE (? IS NULL OR g.tenant_id=?) ORDER BY g.created_at DESC LIMIT 100").bind(tenantId,tenantId).all(),
    d.prepare("SELECT status,COUNT(*) count FROM desktop_sync_operations GROUP BY status").all(),
  ]);
  return Response.json({admin:auth.admin,summary,companies:companies.results,plans:plans.results,tickets:tickets.results,terminals:terminals.results,audits:audits.results,accessGrants:accessGrants.results,syncHealth:syncHealth.results});
}

type PostBody={action?:"plan"|"ticket"|"access";tenantId?:string;name?:string;code?:string;price?:number;billingPeriod?:string;maxBranches?:number;maxUsers?:number;maxTerminals?:number;maxProducts?:number;offlineEnabled?:boolean;subject?:string;description?:string;priority?:string;reason?:string;ticketId?:string;minutes?:number};
export async function POST(req:Request){
  const auth=await authorize(req,true);if(auth.error)return auth.error;const admin=auth.admin!,d=getRuntimeEnv().DB,p=await req.json() as PostBody;
  if(p.action==="plan"){if(admin.role!=="platform_owner")return Response.json({error:"Solo el propietario puede crear planes"},{status:403});if(!p.name?.trim()||!p.code?.trim()||Number(p.maxBranches)<1||Number(p.maxUsers)<1||Number(p.maxTerminals)<1||Number(p.maxProducts)<1)return Response.json({error:"Complete nombre, código y límites válidos"},{status:400});const id=randomUUID();await d.batch([d.prepare("INSERT INTO saas_plans(id,code,name,price_minor,billing_period,max_branches,max_users,max_terminals,max_products,offline_enabled) VALUES(?,?,?,?,?,?,?,?,?,?)").bind(id,p.code.trim().toLowerCase(),p.name.trim(),Math.round(Number(p.price||0)*100),p.billingPeriod==="yearly"?"yearly":"monthly",p.maxBranches,p.maxUsers,p.maxTerminals,p.maxProducts,p.offlineEnabled?1:0),audit(req,admin.id,null,"create","plan",id,"Creación de plan",p)]);return Response.json({id},{status:201})}
  if(!p.tenantId||!await d.prepare("SELECT id FROM tenants WHERE id=?").bind(p.tenantId).first())return Response.json({error:"Empresa inválida"},{status:400});
  if(p.action==="ticket"){if(!p.subject?.trim()||!p.description?.trim())return Response.json({error:"Asunto y descripción son obligatorios"},{status:400});const id=randomUUID(),number=`SOP-${Date.now().toString().slice(-8)}`;await d.batch([d.prepare("INSERT INTO platform_support_tickets(id,tenant_id,number,subject,description,priority,assigned_to,created_by_email) VALUES(?,?,?,?,?,?,?,?)").bind(id,p.tenantId,number,p.subject.trim(),p.description.trim(),["low","normal","high","critical"].includes(p.priority||"")?p.priority:"normal",admin.id,admin.email),audit(req,admin.id,p.tenantId,"create","support_ticket",id,"Caso de soporte creado",{number})]);return Response.json({id,number},{status:201})}
  if(p.action==="access"){if(!p.reason?.trim()||p.reason.trim().length<12)return Response.json({error:"Explique el motivo del acceso excepcional (mínimo 12 caracteres)"},{status:400});if(p.ticketId&&!await d.prepare("SELECT id FROM platform_support_tickets WHERE id=? AND tenant_id=?").bind(p.ticketId,p.tenantId).first())return Response.json({error:"El caso de soporte no corresponde a la empresa"},{status:403});const minutes=Math.min(120,Math.max(5,Number(p.minutes||30))),id=randomUUID();await d.batch([d.prepare("UPDATE platform_access_grants SET status='expired' WHERE platform_admin_id=? AND tenant_id=? AND status='active'").bind(admin.id,p.tenantId),d.prepare("INSERT INTO platform_access_grants(id,tenant_id,platform_admin_id,reason,ticket_id,expires_at) VALUES(?,?,?,?,?,datetime('now',?))").bind(id,p.tenantId,admin.id,p.reason.trim(),p.ticketId||null,`+${minutes} minutes`),audit(req,admin.id,p.tenantId,"grant","exceptional_access",id,p.reason.trim(),{minutes,ticketId:p.ticketId})]);return Response.json({id,minutes},{status:201})}
  return Response.json({error:"Acción inválida"},{status:400});
}

type PatchBody={action?:"subscription"|"suspend"|"ticket"|"terminal"|"revoke_access";tenantId?:string;planId?:string;status?:string;trialDays?:number;reason?:string;ticketId?:string;resolution?:string;terminalId?:string;active?:boolean;grantId?:string};
export async function PATCH(req:Request){
  const auth=await authorize(req,true);if(auth.error)return auth.error;const admin=auth.admin!,d=getRuntimeEnv().DB,p=await req.json() as PatchBody;
  if(p.action==="subscription"){if(admin.role!=="platform_owner"||!p.tenantId||!p.planId||!await d.prepare("SELECT id FROM saas_plans WHERE id=? AND active=1").bind(p.planId).first())return Response.json({error:"Plan, empresa o autorización inválidos"},{status:403});const status=["trial","active","past_due","cancelled"].includes(p.status||"")?p.status:"active",trialDays=Math.min(90,Math.max(1,Number(p.trialDays||14)));await d.batch([d.prepare("INSERT INTO tenant_subscriptions(id,tenant_id,plan_id,status,trial_ends_at,current_period_start,current_period_end,updated_by) VALUES(?,?,?,?,datetime('now',?),date('now'),date('now','+1 month'),?) ON CONFLICT(tenant_id) DO UPDATE SET plan_id=excluded.plan_id,status=excluded.status,trial_ends_at=excluded.trial_ends_at,current_period_start=excluded.current_period_start,current_period_end=excluded.current_period_end,updated_by=excluded.updated_by,updated_at=CURRENT_TIMESTAMP").bind(randomUUID(),p.tenantId,p.planId,status,`+${trialDays} days`,admin.id),d.prepare("UPDATE tenants SET status=? WHERE id=?").bind(status==="cancelled"?"inactive":"active",p.tenantId),audit(req,admin.id,p.tenantId,"update","subscription",p.tenantId,p.reason?.trim()||"Cambio de plan o periodo",{planId:p.planId,status,trialDays})]);return Response.json({updated:true})}
  if(p.action==="suspend"){if(admin.role!=="platform_owner"||!p.tenantId||!p.reason?.trim())return Response.json({error:"Solo el propietario puede suspender y debe indicar el motivo"},{status:403});const suspend=p.status!=="active";await d.batch([d.prepare("UPDATE tenants SET status=? WHERE id=?").bind(suspend?"suspended":"active",p.tenantId),d.prepare("UPDATE tenant_subscriptions SET status=?,suspended_reason=?,suspended_at=?,updated_by=?,updated_at=CURRENT_TIMESTAMP WHERE tenant_id=?").bind(suspend?"suspended":"active",suspend?p.reason:null,suspend?new Date().toISOString():null,admin.id,p.tenantId),audit(req,admin.id,p.tenantId,suspend?"suspend":"reactivate","tenant",p.tenantId,p.reason,{})]);return Response.json({suspended:suspend})}
  if(p.action==="ticket"){if(!p.ticketId||!p.status||!["open","in_progress","waiting_customer","resolved","closed"].includes(p.status))return Response.json({error:"Caso o estado inválido"},{status:400});const ticket=await d.prepare("SELECT tenant_id tenantId FROM platform_support_tickets WHERE id=?").bind(p.ticketId).first<{tenantId:string}>();if(!ticket)return Response.json({error:"Caso no encontrado"},{status:404});await d.batch([d.prepare("UPDATE platform_support_tickets SET status=?,resolution=COALESCE(?,resolution),resolved_at=CASE WHEN ? IN ('resolved','closed') THEN CURRENT_TIMESTAMP ELSE resolved_at END,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(p.status,p.resolution||null,p.status,p.ticketId),audit(req,admin.id,ticket.tenantId,"update","support_ticket",p.ticketId,p.resolution||`Estado ${p.status}`,{status:p.status})]);return Response.json({updated:true})}
  if(p.action==="terminal"){const terminal=await d.prepare("SELECT tenant_id tenantId FROM terminals WHERE id=? AND (? IS NULL OR tenant_id=?)").bind(p.terminalId,p.tenantId||null,p.tenantId||null).first<{tenantId:string}>();if(!terminal)return Response.json({error:"Terminal no encontrada"},{status:404});await d.batch([d.prepare("UPDATE terminals SET status=? WHERE id=?").bind(p.active===false?"blocked":"active",p.terminalId),d.prepare("UPDATE desktop_terminal_credentials SET status=? WHERE terminal_id=?").bind(p.active===false?"revoked":"active",p.terminalId),audit(req,admin.id,terminal.tenantId,p.active===false?"block":"activate","terminal",p.terminalId!,p.reason||"Control operativo de terminal",{})]);return Response.json({updated:true})}
  if(p.action==="revoke_access"){const grant=await d.prepare("SELECT tenant_id tenantId FROM platform_access_grants WHERE id=? AND platform_admin_id=? AND status='active'").bind(p.grantId,admin.id).first<{tenantId:string}>();if(!grant)return Response.json({error:"Acceso no disponible"},{status:404});await d.batch([d.prepare("UPDATE platform_access_grants SET status='revoked',revoked_at=CURRENT_TIMESTAMP WHERE id=?").bind(p.grantId),audit(req,admin.id,grant.tenantId,"revoke","exceptional_access",p.grantId!,p.reason||"Acceso cerrado por el administrador",{})]);return Response.json({updated:true})}
  return Response.json({error:"Acción inválida"},{status:400});
}
