import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fork } from "node:child_process";
import { createServer } from "node:http";
import { LocalPOSDatabase,receiptBytes } from "../src/database.mjs";
import { SyncEngine } from "../src/sync.mjs";
const snapshot={terminal:{id:"terminal-test",code:"WIN-01"},settings:{company:"POS360",branch:"Centro"},catalogVersion:1,products:[{id:"p1",sku:"P1",barcode:"7701",barcodes:["ALT1"],name:"Producto pesado",priceMinor:1000,costMinor:600,stock:20,trackInventory:1,version:1}]};
async function localDb(){const dir=await mkdtemp(join(tmpdir(),"pos360-win-")),path=join(dir,"pos.sqlite"),db=new LocalPOSDatabase(path);db.importCatalog(snapshot);return{db,path}}
test("local sales are atomic, exact and idempotent",async()=>{const{db}=await localDb(),input={operationId:"terminal-test-op-1",items:[{productId:"p1",quantity:1.5}],payments:[{method:"cash",amountMinor:500},{method:"cash",amountMinor:1000}]},first=db.createSale(input),second=db.createSale(input);assert.equal(first.id,second.id);assert.equal(second.duplicate,true);assert.equal(db.findProduct("ALT1").stock,18.5);assert.deepEqual(db.stats(),{sales:1,pending:1,conflicts:0,integrity:"ok"});assert.throws(()=>db.createSale({operationId:"bad",items:[{productId:"p1",quantity:1}],payments:[{method:"cash",amountMinor:1}]}),/pagos locales/);assert.equal(db.findProduct("p1").stock,18.5);db.close()});
test("a real network cut leaves the durable queue and later syncs once",async()=>{const{db}=await localDb();db.createSale({operationId:"offline-op",items:[{productId:"p1",quantity:1}],payments:[{method:"cash",amountMinor:1000}]});const offline=new SyncEngine({database:db,baseUrl:"http://127.0.0.1:1",token:"x"}),failed=await offline.push();assert.equal(failed.offline,true);assert.equal(db.stats().pending,1);await new Promise(r=>setTimeout(r,5200));let calls=0;const server=createServer((req,res)=>{calls++;let body="";req.on("data",x=>body+=x);req.on("end",()=>{const op=JSON.parse(body).operations[0];res.setHeader("content-type","application/json");res.end(JSON.stringify({results:[{id:op.id,status:"applied",serverEntityId:"server-sale-1"}]}))})});await new Promise(r=>server.listen(0,"127.0.0.1",r));const port=server.address().port,synced=await new SyncEngine({database:db,baseUrl:`http://127.0.0.1:${port}`,token:"x"}).push();assert.equal(synced.sent,1);assert.equal(calls,1);assert.equal(db.stats().pending,0);await new SyncEngine({database:db,baseUrl:`http://127.0.0.1:${port}`,token:"x"}).push();assert.equal(calls,1);server.close();db.close()});
test("SIGKILL during a SQLite transaction rolls back after restart",async()=>{const{db,path}=await localDb();db.close();const child=fork(new URL("./crash-worker.mjs",import.meta.url),[path],{stdio:["ignore","ignore","ignore","ipc"]});await new Promise((resolve,reject)=>{child.once("message",resolve);child.once("error",reject)});child.kill("SIGKILL");await new Promise(resolve=>child.once("exit",resolve));const reopened=new LocalPOSDatabase(path);assert.equal(reopened.findProduct("p1").stock,20);assert.equal(reopened.stats().sales,0);assert.equal(reopened.stats().integrity,"ok");reopened.close()});
test("thermal receipt contains initialization, drawer pulse and cut",()=>{const bytes=receiptBytes({operationId:"op",total:1000,lines:[{name:"Producto",quantity:1,total:1000}]});assert.ok(bytes.includes(Buffer.from("POS360")));assert.ok(bytes.includes(Buffer.from([0x1b,0x70])));assert.ok(bytes.includes(Buffer.from([0x1d,0x56])))});
