import { requireAccess } from "../../../db/authz";
import { getRuntimeEnv } from "../../../db/runtime-env";

const validDate=(value:string|null,fallback:string)=>value&&/^\d{4}-\d{2}-\d{2}$/.test(value)?value:fallback;
export async function GET(req:Request){
  const u=new URL(req.url),dashboard=u.searchParams.get("scope")==="dashboard",access=await requireAccess(req,dashboard?"dashboard":"reports");if(access.error)return access.error;
  const d=getRuntimeEnv().DB,T=access.user.tenantId,B=access.user.branchId,today=new Date().toISOString().slice(0,10),start=validDate(u.searchParams.get("from"),`${today.slice(0,8)}01`),end=validDate(u.searchParams.get("to"),today),warehouseId=u.searchParams.get("warehouseId")||"",requestedUser=u.searchParams.get("userId")||"",role=access.user.role;
  if(start>end)return Response.json({error:"El rango de fechas no es válido"},{status:400});
  if(warehouseId){const warehouse=await d.prepare("SELECT id FROM warehouses WHERE id=? AND tenant_id=? AND branch_id=? AND active=1").bind(warehouseId,T,B).first();if(!warehouse)return Response.json({error:"La bodega no pertenece a la empresa y sede activas"},{status:403})}
  const mayFilterUsers=["owner","admin","supervisor","auditor"].includes(role),userId=mayFilterUsers?requestedUser:access.user.id;
  if(userId){const target=await d.prepare("SELECT u.id FROM app_users u WHERE u.id=? AND u.tenant_id=? AND u.active=1 AND (NOT EXISTS(SELECT 1 FROM user_branch_access a WHERE a.user_id=u.id) OR EXISTS(SELECT 1 FROM user_branch_access a WHERE a.user_id=u.id AND a.branch_id=?))").bind(userId,T,B).first();if(!target)return Response.json({error:"El usuario no pertenece a la empresa o sede activa"},{status:403})}
  const full=["owner","admin","supervisor","auditor"].includes(role),canSales=full||dashboard,canCash=full||dashboard,canAudit=!dashboard&&["owner","admin","auditor"].includes(role),canPurchases=!dashboard&&(full||role==="purchasing"),canInventory=canPurchases;
  const saleWhere="s.tenant_id=? AND s.branch_id=? AND s.created_at>=? AND s.created_at<datetime(?,'+1 day') AND (?='' OR s.warehouse_id=?) AND (?='' OR s.user_id=?)",saleBind=[T,B,start,end,warehouseId,warehouseId,userId,userId];
  const empty={results:[]};
  const [summary,daily,payments,topProducts,inventory,outOfStock,purchases,cash,portfolio,returns,audit,warehouses,users]=await Promise.all([
    canSales?d.prepare(`SELECT COALESCE(SUM(s.total_minor),0)/100.0 sales,COUNT(*) transactions,COALESCE(AVG(s.total_minor),0)/100.0 averageTicket,COALESCE(SUM(s.total_minor-COALESCE((SELECT SUM(ABS(l.quantity)*l.unit_cost_minor) FROM inventory_ledger l WHERE l.source_type='sale' AND l.source_id=s.id),0)),0)/100.0 profit FROM sales s WHERE ${saleWhere} AND s.status='completed'`).bind(...saleBind).first():null,
    canSales?d.prepare(`SELECT date(s.created_at) day,SUM(s.total_minor)/100.0 sales,COUNT(*) transactions FROM sales s WHERE ${saleWhere} AND s.status='completed' GROUP BY date(s.created_at) ORDER BY day`).bind(...saleBind).all():empty,
    canSales?d.prepare(`SELECT p.method,SUM(p.amount_minor)/100.0 total,COUNT(DISTINCT p.sale_id) transactions FROM sale_payments p JOIN sales s ON s.id=p.sale_id WHERE ${saleWhere} AND s.status='completed' GROUP BY p.method ORDER BY total DESC`).bind(...saleBind).all():empty,
    canSales?d.prepare(`SELECT p.id,p.name,SUM(l.quantity) quantity,SUM(l.line_total_minor)/100.0 sales FROM sale_lines l JOIN sales s ON s.id=l.sale_id JOIN products p ON p.id=l.product_id WHERE ${saleWhere} AND s.status='completed' GROUP BY p.id,p.name ORDER BY sales DESC LIMIT 10`).bind(...saleBind).all():empty,
    canInventory?d.prepare("SELECT COALESCE(SUM(b.quantity*b.average_cost_minor),0)/100.0 valuation,COALESCE(SUM(b.quantity),0) units,COUNT(DISTINCT b.product_id) products FROM inventory_balances b JOIN warehouses w ON w.id=b.warehouse_id WHERE b.tenant_id=? AND w.branch_id=? AND (?='' OR b.warehouse_id=?)").bind(T,B,warehouseId,warehouseId).first():null,
    canInventory?d.prepare("SELECT p.id,p.name,p.sku,w.name warehouse,COALESCE(b.quantity,0) quantity FROM products p JOIN warehouses w ON w.tenant_id=p.tenant_id AND w.branch_id=? LEFT JOIN inventory_balances b ON b.product_id=p.id AND b.warehouse_id=w.id AND b.variant_id IS NULL WHERE p.tenant_id=? AND p.active=1 AND p.track_inventory=1 AND (?='' OR w.id=?) AND COALESCE(b.quantity,0)<=0 ORDER BY p.name LIMIT 30").bind(B,T,warehouseId,warehouseId).all():empty,
    canPurchases?d.prepare("SELECT COALESCE((SELECT SUM(r.total_minor) FROM purchase_receipts r JOIN purchase_orders x ON x.id=r.order_id WHERE r.tenant_id=? AND x.branch_id=? AND r.created_at>=? AND r.created_at<datetime(?,'+1 day') AND (?='' OR r.warehouse_id=?)),0)/100.0 received,(SELECT COUNT(DISTINCT r.order_id) FROM purchase_receipts r JOIN purchase_orders x ON x.id=r.order_id WHERE r.tenant_id=? AND x.branch_id=? AND r.created_at>=? AND r.created_at<datetime(?,'+1 day') AND (?='' OR r.warehouse_id=?)) orders,COALESCE((SELECT SUM(po.total_minor) FROM purchase_orders po WHERE po.tenant_id=? AND po.branch_id=? AND po.status IN ('approved','partial') AND (?='' OR po.warehouse_id=?)),0)/100.0 pending").bind(T,B,start,end,warehouseId,warehouseId,T,B,start,end,warehouseId,warehouseId,T,B,warehouseId,warehouseId).first():null,
    canCash?d.prepare("SELECT COALESCE(SUM(CASE WHEN m.affects_cash=1 THEN m.amount_minor ELSE 0 END),0)/100.0 movementTotal,COUNT(DISTINCT s.id) sessions,COALESCE(SUM(CASE WHEN s.difference_minor<>0 THEN s.difference_minor ELSE 0 END),0)/100.0 differences FROM cash_sessions s LEFT JOIN cash_movements m ON m.session_id=s.id AND m.created_at>=? AND m.created_at<datetime(?,'+1 day') WHERE s.tenant_id=? AND s.branch_id=? AND (?='' OR s.user_id=?)").bind(start,end,T,B,userId,userId).first():null,
    full?d.prepare("SELECT COALESCE(SUM(r.balance_minor),0)/100.0 balance,COALESCE(SUM(CASE WHEN r.due_date<date('now') THEN r.balance_minor ELSE 0 END),0)/100.0 overdue,COUNT(CASE WHEN r.balance_minor>0 THEN 1 END) openAccounts FROM receivables r WHERE r.tenant_id=? AND r.branch_id=?").bind(T,B).first():null,
    canSales?d.prepare("SELECT COALESCE(SUM(sr.total),0) total,COUNT(*) count FROM sale_returns sr JOIN sales s ON s.id=sr.sale_id WHERE sr.tenant_id=? AND s.branch_id=? AND sr.created_at>=? AND sr.created_at<datetime(?,'+1 day') AND (?='' OR s.user_id=?)").bind(T,B,start,end,userId,userId).first():null,
    canAudit?d.prepare("SELECT l.action,l.entity_type entityType,l.entity_id entityId,l.details,l.created_at createdAt,COALESCE(u.display_name,'Sistema') userName FROM audit_logs l LEFT JOIN app_users u ON u.id=l.user_id WHERE l.tenant_id=? AND l.created_at>=? AND l.created_at<datetime(?,'+1 day') AND (?='' OR l.user_id=?) ORDER BY l.created_at DESC LIMIT 50").bind(T,start,end,userId,userId).all():empty,
    d.prepare("SELECT id,name FROM warehouses WHERE tenant_id=? AND branch_id=? AND active=1 ORDER BY name").bind(T,B).all(),
    mayFilterUsers?d.prepare("SELECT DISTINCT u.id,u.display_name name FROM app_users u LEFT JOIN user_branch_access a ON a.user_id=u.id WHERE u.tenant_id=? AND u.active=1 AND (a.branch_id=? OR NOT EXISTS(SELECT 1 FROM user_branch_access x WHERE x.user_id=u.id)) ORDER BY u.display_name").bind(T,B).all():empty,
  ]);
  return Response.json({filters:{from:start,to:end,tenantId:T,branchId:B,warehouseId,userId},permissions:{sales:canSales,inventory:canInventory,purchases:canPurchases,cash:canCash,portfolio:full,returns:canSales,audit:canAudit},summary,daily:daily.results,payments:payments.results,topProducts:topProducts.results,inventory,outOfStock:outOfStock.results,purchases,cash,portfolio,returns,audit:audit.results,options:{warehouses:warehouses.results,users:users.results}})
}
