import {randomUUID} from "node:crypto";
/* eslint-disable @typescript-eslint/no-explicit-any */
import {requireAccess} from "../../../db/authz";
import {getRuntimeEnv} from "../../../db/runtime-env";
import {parseMoney} from "../../../db/money";

const hash=async(value:string)=>Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value)))).map(x=>x.toString(16).padStart(2,"0")).join("");
const escape=(value:unknown)=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]!));
const graphic=(document:{number:string;documentType:string;issueDate:string;issuer:any;customer:any;lines:any[];subtotalMinor:number;taxMinor:number;totalMinor:number;currency:string;status:string;cufe?:string})=>`<!doctype html><html lang="es"><head><meta charset="utf-8"><title>${escape(document.number)}</title><style>body{font-family:Arial;margin:32px;color:#142b3b}header{display:flex;justify-content:space-between;border-bottom:3px solid #0b887e;padding-bottom:18px}table{width:100%;border-collapse:collapse;margin:24px 0}th,td{padding:9px;border-bottom:1px solid #ddd;text-align:left}.right{text-align:right}.totals{margin-left:auto;width:320px}.legal{margin-top:30px;font-size:11px;color:#52636d}</style></head><body><header><div><h1>${escape(document.issuer.name||"POS360")}</h1><p>NIT ${escape(document.issuer.nit)}</p></div><div><b>${escape(document.documentType.replaceAll("_"," ").toUpperCase())}</b><h2>${escape(document.number)}</h2><p>${escape(document.issueDate)}</p></div></header><p><b>Adquirente:</b> ${escape(document.customer.name||"Consumidor final")} · ${escape(document.customer.documentNumber||"")}</p><table><thead><tr><th>Descripción</th><th class="right">Cant.</th><th class="right">Precio</th><th class="right">Total</th></tr></thead><tbody>${document.lines.map(line=>`<tr><td>${escape(line.name)}</td><td class="right">${escape(line.quantity)}</td><td class="right">${(line.unitPriceMinor/100).toLocaleString("es-CO")}</td><td class="right">${(line.lineTotalMinor/100).toLocaleString("es-CO")}</td></tr>`).join("")}</tbody></table><div class="totals"><p>Subtotal: <b>${document.currency} ${(document.subtotalMinor/100).toLocaleString("es-CO")}</b></p><p>Impuestos incluidos: <b>${document.currency} ${(document.taxMinor/100).toLocaleString("es-CO")}</b></p><h2>Total: ${document.currency} ${(document.totalMinor/100).toLocaleString("es-CO")}</h2></div><div class="legal"><p>Estado electrónico: ${escape(document.status)}</p><p>CUFE/CUDE: ${escape(document.cufe||"Pendiente de validación")}</p><p>Representación gráfica generada por POS360. El archivo electrónico validado es el documento con valor fiscal.</p></div></body></html>`;
const event=(d:any,T:string,documentId:string,userId:string|null,type:string,from:string|null,to:string,details:unknown={})=>d.prepare("INSERT INTO electronic_document_events(id,tenant_id,document_id,user_id,event_type,from_status,to_status,details) VALUES(?,?,?,?,?,?,?,?)").bind(randomUUID(),T,documentId,userId,type,from,to,JSON.stringify(details));

export async function GET(req:Request){
  const access=await requireAccess(req,"settings");if(access.error)return access.error;const d=getRuntimeEnv().DB,T=access.user.tenantId,url=new URL(req.url),documentId=url.searchParams.get("documentId"),format=url.searchParams.get("format");
  if(documentId){const document=await d.prepare("SELECT x.*,r.authorization_number authorizationNumber,r.prefix,p.name providerName FROM electronic_documents x LEFT JOIN electronic_resolutions r ON r.id=x.resolution_id LEFT JOIN electronic_billing_providers p ON p.id=x.provider_id WHERE x.id=? AND x.tenant_id=?").bind(documentId,T).first<any>();if(!document)return Response.json({error:"Documento electrónico no encontrado"},{status:404});if(format==="html"){const file=await d.prepare("SELECT content_base64 contentBase64 FROM electronic_document_files WHERE tenant_id=? AND document_id=? AND file_type='graphic_html'").bind(T,documentId).first<{contentBase64:string}>();if(!file)return new Response("Representación no disponible",{status:404});return new Response(atob(file.contentBase64),{headers:{"content-type":"text/html; charset=utf-8","content-disposition":`inline; filename=${document.number}.html`}})}const [attempts,events,files]=await Promise.all([d.prepare("SELECT attempt_number attemptNumber,result,http_status httpStatus,error_code errorCode,error_message errorMessage,started_at startedAt,completed_at completedAt FROM electronic_document_attempts WHERE document_id=? ORDER BY attempt_number DESC").bind(documentId).all(),d.prepare("SELECT event_type eventType,from_status fromStatus,to_status toStatus,details,created_at createdAt FROM electronic_document_events WHERE document_id=? ORDER BY created_at DESC").bind(documentId).all(),d.prepare("SELECT id,file_type fileType,storage_key storageKey,content_type contentType,checksum_sha256 checksum,size_bytes sizeBytes,created_at createdAt FROM electronic_document_files WHERE document_id=? ORDER BY created_at").bind(documentId).all()]);return Response.json({document:{...document,customerSnapshot:JSON.parse(document.customer_snapshot),issuerSnapshot:JSON.parse(document.issuer_snapshot),linesSnapshot:JSON.parse(document.lines_snapshot)},attempts:attempts.results,events:events.results,files:files.results})}
  const [settings,resolutions,providers,documents,sales,contingencies,summary]=await Promise.all([
    d.prepare("SELECT t.name,bs.nit,bs.currency,t.country,bs.timezone FROM tenants t LEFT JOIN business_settings bs ON bs.tenant_id=t.id WHERE t.id=?").bind(T).first(),
    d.prepare("SELECT r.id,r.branch_id branchId,b.name branchName,r.document_type documentType,r.authorization_number authorizationNumber,r.prefix,r.range_from rangeFrom,r.range_to rangeTo,r.next_number nextNumber,r.valid_from validFrom,r.valid_until validUntil,r.active FROM electronic_resolutions r LEFT JOIN branches b ON b.id=r.branch_id WHERE r.tenant_id=? ORDER BY r.active DESC,r.valid_until").bind(T).all(),
    d.prepare("SELECT id,name,provider_type providerType,environment,endpoint,software_id softwareId,test_set_id testSetId,active,updated_at updatedAt FROM electronic_billing_providers WHERE tenant_id=? ORDER BY active DESC").bind(T).all(),
    d.prepare("SELECT x.id,x.sale_id saleId,x.parent_document_id parentDocumentId,x.document_type documentType,x.number,x.issue_date issueDate,x.status,x.total_minor totalMinor,x.cufe,x.provider_status_code providerStatusCode,x.provider_message providerMessage,x.retry_count retryCount,x.next_retry_at nextRetryAt,x.created_at createdAt,COALESCE(c.name,'Consumidor final') customerName FROM electronic_documents x LEFT JOIN sales s ON s.id=x.sale_id LEFT JOIN customers c ON c.id=s.customer_id WHERE x.tenant_id=? ORDER BY x.created_at DESC LIMIT 100").bind(T).all(),
    d.prepare("SELECT s.id,s.total_minor totalMinor,s.created_at createdAt,COALESCE(c.name,'Consumidor final') customerName,(SELECT COUNT(*) FROM electronic_documents x WHERE x.sale_id=s.id AND x.document_type IN ('invoice','equivalent')) documentCount FROM sales s LEFT JOIN customers c ON c.id=s.customer_id WHERE s.tenant_id=? AND s.status='completed' ORDER BY s.created_at DESC LIMIT 50").bind(T).all(),
    d.prepare("SELECT id,contingency_type contingencyType,reason,evidence,status,opened_at openedAt,closed_at closedAt FROM electronic_contingencies WHERE tenant_id=? ORDER BY opened_at DESC LIMIT 20").bind(T).all(),
    d.prepare("SELECT COUNT(*) total,SUM(CASE WHEN status IN ('accepted','accepted_with_warnings') THEN 1 ELSE 0 END) accepted,SUM(CASE WHEN status='rejected' THEN 1 ELSE 0 END) rejected,SUM(CASE WHEN status IN ('queued','sending') THEN 1 ELSE 0 END) pending,SUM(CASE WHEN status='contingency' THEN 1 ELSE 0 END) contingency FROM electronic_documents WHERE tenant_id=?").bind(T).first(),
  ]);return Response.json({settings,resolutions:resolutions.results,providers:providers.results,documents:documents.results,sales:sales.results,contingencies:contingencies.results,summary});
}

type Body={action?:string;name?:string;providerType?:string;environment?:string;endpoint?:string;credentialReference?:string;softwareId?:string;testSetId?:string;branchId?:string;documentType?:string;authorizationNumber?:string;prefix?:string;rangeFrom?:number;rangeTo?:number;nextNumber?:number;validFrom?:string;validUntil?:string;technicalKeyReference?:string;saleId?:string;parentDocumentId?:string;reason?:string;amount?:number;idempotencyKey?:string;documentId?:string;contingencyType?:string;evidence?:unknown[];contingencyId?:string};
export async function POST(req:Request){
  const access=await requireAccess(req,"settings","create");if(access.error)return access.error;const p=await req.json() as Body,d=getRuntimeEnv().DB,T=access.user.tenantId,B=access.user.branchId,user=access.user.id;
  if(p.action==="provider"){if(!["owner","admin"].includes(access.user.role))return Response.json({error:"Solo administración configura el proveedor tecnológico"},{status:403});if(!p.name?.trim()||!["technology_provider","direct_dian","sandbox"].includes(p.providerType||""))return Response.json({error:"Proveedor y tipo requeridos"},{status:400});if(p.environment==="production"&&(!p.credentialReference||!p.softwareId))return Response.json({error:"Producción requiere referencia segura de credencial y software ID"},{status:400});const id=randomUUID();await d.batch([d.prepare("UPDATE electronic_billing_providers SET active=0 WHERE tenant_id=?").bind(T),d.prepare("INSERT INTO electronic_billing_providers(id,tenant_id,name,provider_type,environment,endpoint,credential_reference,software_id,test_set_id) VALUES(?,?,?,?,?,?,?,?,?)").bind(id,T,p.name.trim(),p.providerType,p.environment==="production"?"production":"habilitation",p.endpoint||null,p.credentialReference||null,p.softwareId||null,p.testSetId||null)]);return Response.json({id},{status:201})}
  if(p.action==="resolution"){if(!["owner","admin"].includes(access.user.role))return Response.json({error:"Solo administración configura resoluciones"},{status:403});if(!p.authorizationNumber?.trim()||!p.prefix?.trim()||!["invoice","equivalent","contingency"].includes(p.documentType||"")||Number(p.rangeFrom)<1||Number(p.rangeTo)<Number(p.rangeFrom)||!p.validFrom||!p.validUntil)return Response.json({error:"Resolución, prefijo, rango y vigencia son obligatorios"},{status:400});if(p.branchId&&!await d.prepare("SELECT id FROM branches WHERE id=? AND tenant_id=?").bind(p.branchId,T).first())return Response.json({error:"La sede no pertenece a la empresa"},{status:403});const id=randomUUID(),next=Math.max(Number(p.rangeFrom),Number(p.nextNumber||p.rangeFrom));await d.prepare("INSERT INTO electronic_resolutions(id,tenant_id,branch_id,document_type,authorization_number,prefix,range_from,range_to,next_number,valid_from,valid_until,technical_key_reference) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)").bind(id,T,p.branchId||null,p.documentType,p.authorizationNumber.trim(),p.prefix.trim().toUpperCase(),p.rangeFrom,p.rangeTo,next,p.validFrom,p.validUntil,p.technicalKeyReference||null).run();return Response.json({id},{status:201})}
  if(p.action==="contingency"){if(!p.reason?.trim()||!p.contingencyType)return Response.json({error:"Tipo y motivo de contingencia requeridos"},{status:400});const id=randomUUID();await d.prepare("INSERT INTO electronic_contingencies(id,tenant_id,branch_id,contingency_type,reason,evidence,opened_by) VALUES(?,?,?,?,?,?,?)").bind(id,T,B,p.contingencyType,p.reason.trim(),JSON.stringify(p.evidence||[]),user).run();return Response.json({id},{status:201})}
  if(p.action==="closeContingency"){const current=await d.prepare("SELECT id FROM electronic_contingencies WHERE id=? AND tenant_id=? AND status='open'").bind(p.contingencyId,T).first();if(!current)return Response.json({error:"Contingencia no disponible"},{status:404});await d.prepare("UPDATE electronic_contingencies SET status='closed',closed_at=CURRENT_TIMESTAMP WHERE id=?").bind(p.contingencyId).run();return Response.json({closed:true})}
  if(p.action==="retry"){const document=await d.prepare("SELECT id,status FROM electronic_documents WHERE id=? AND tenant_id=? AND status IN ('rejected','queued','contingency')").bind(p.documentId,T).first<{id:string;status:string}>();if(!document)return Response.json({error:"Documento no disponible para reintento"},{status:404});await d.batch([d.prepare("UPDATE electronic_documents SET status='queued',next_retry_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(document.id),event(d,T,document.id,user,"manual_retry",document.status,"queued",{reason:p.reason||"Reintento manual"})]);return Response.json({queued:true})}
  if(!["issue","note"].includes(p.action||""))return Response.json({error:"Acción inválida"},{status:400});
  const type=p.action==="note"?(p.documentType==="debit_note"?"debit_note":"credit_note"):(p.documentType==="equivalent"?"equivalent":"invoice"),idempotency=p.idempotencyKey?.trim()||`${type}:${p.saleId||p.parentDocumentId}`;
  const duplicate=await d.prepare("SELECT id,number,status FROM electronic_documents WHERE tenant_id=? AND idempotency_key=?").bind(T,idempotency).first();if(duplicate)return Response.json({document:duplicate,duplicate:true});
  const parent=p.action==="note"?await d.prepare("SELECT id,branch_id branchId,sale_id saleId,total_minor totalMinor,status FROM electronic_documents WHERE id=? AND tenant_id=? AND document_type IN ('invoice','equivalent') AND status IN ('accepted','accepted_with_warnings')").bind(p.parentDocumentId,T).first<any>():null;
  if(p.action==="note"&&!parent)return Response.json({error:"La nota requiere un documento electrónico aceptado"},{status:409});
  const saleId=p.saleId||parent?.saleId,sale=await d.prepare("SELECT s.id,s.branch_id branchId,s.customer_id customerId,s.subtotal_minor subtotalMinor,s.total_minor totalMinor,s.created_at createdAt,COALESCE(c.name,'Consumidor final') customerName,c.document_number documentNumber,c.email,c.phone FROM sales s LEFT JOIN customers c ON c.id=s.customer_id WHERE s.id=? AND s.tenant_id=? AND s.status='completed'").bind(saleId,T).first<any>();if(!sale)return Response.json({error:"Venta válida requerida"},{status:404});
  const resolutionType=type==="equivalent"?"equivalent":"invoice",resolution=await d.prepare("SELECT id,prefix,next_number nextNumber,range_to rangeTo FROM electronic_resolutions WHERE tenant_id=? AND document_type=? AND active=1 AND next_number<=range_to AND valid_from<=date('now') AND valid_until>=date('now') AND (branch_id IS NULL OR branch_id=?) ORDER BY branch_id DESC,valid_until LIMIT 1").bind(T,resolutionType,sale.branchId).first<any>();if(!resolution)return Response.json({error:`No hay numeración vigente disponible para ${resolutionType}`},{status:409});
  const provider=await d.prepare("SELECT id,name,provider_type providerType,environment,endpoint,credential_reference credentialReference FROM electronic_billing_providers WHERE tenant_id=? AND active=1").bind(T).first<any>();if(!provider)return Response.json({error:"Configure un proveedor tecnológico antes de emitir"},{status:409});
  const [linesResult,issuer]=await Promise.all([d.prepare("SELECT l.product_id productId,p.sku,p.name,l.quantity,l.unit_price_minor unitPriceMinor,l.line_total_minor lineTotalMinor,COALESCE(t.rate,0) taxRate,COALESCE(t.included_in_price,1) taxIncluded FROM sale_lines l JOIN products p ON p.id=l.product_id LEFT JOIN tax_rates t ON t.id=p.tax_id WHERE l.sale_id=?").bind(sale.id).all<any>(),d.prepare("SELECT t.name,bs.nit,t.country,bs.currency,bs.timezone FROM tenants t LEFT JOIN business_settings bs ON bs.tenant_id=t.id WHERE t.id=?").bind(T).first<any>()]),lines=linesResult.results,taxMinor=lines.reduce((sum:number,line:any)=>sum+Math.round(line.taxIncluded?line.lineTotalMinor*line.taxRate/(100+line.taxRate):line.lineTotalMinor*line.taxRate/100),0),amount=p.action==="note"?parseMoney(p.amount||0):sale.totalMinor;
  if(p.action==="note"&&(amount<=0||amount>parent.totalMinor))return Response.json({error:"El valor de la nota debe ser positivo y no superar el documento original"},{status:400});
  const id=randomUUID(),number=`${resolution.prefix}${resolution.nextNumber}`,issueDate=new Date().toISOString(),customer={name:sale.customerName,documentNumber:sale.documentNumber||null,email:sale.email||null,phone:sale.phone||null},status=await d.prepare("SELECT id FROM electronic_contingencies WHERE tenant_id=? AND status='open' AND (branch_id IS NULL OR branch_id=?)").bind(T,sale.branchId).first()?"contingency":"queued",snapshot={number,documentType:type,issueDate,issuer,customer,lines,subtotalMinor:p.action==="note"?amount: sale.subtotalMinor,taxMinor:p.action==="note"?0:taxMinor,totalMinor:amount,currency:issuer.currency||"COP",status},html=graphic(snapshot),ubl=JSON.stringify({technicalProfile:type==="equivalent"?"DIAN-DEE-1.0":"DIAN-FEV-1.9",...snapshot,parentDocumentId:p.parentDocumentId||null,resolutionId:resolution.id}),htmlChecksum=await hash(html),ublChecksum=await hash(ubl),stmts=[d.prepare("UPDATE electronic_resolutions SET next_number=next_number+1 WHERE id=? AND next_number=?").bind(resolution.id,resolution.nextNumber),d.prepare("INSERT INTO electronic_documents(id,tenant_id,branch_id,sale_id,parent_document_id,resolution_id,provider_id,document_type,number,issue_date,status,contingency_type,currency,subtotal_minor,tax_minor,total_minor,customer_snapshot,issuer_snapshot,lines_snapshot,next_retry_at,idempotency_key,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(id,T,sale.branchId,sale.id,p.parentDocumentId||null,resolution.id,provider.id,type,number,issueDate,status,status==="contingency"?"active":null,issuer.currency||"COP",snapshot.subtotalMinor,snapshot.taxMinor,snapshot.totalMinor,JSON.stringify(customer),JSON.stringify(issuer),JSON.stringify(lines),status==="queued"?issueDate.replace("T"," ").slice(0,19):null,idempotency,user),d.prepare("INSERT INTO electronic_document_files(id,tenant_id,document_id,file_type,storage_key,content_type,content_base64,checksum_sha256,size_bytes) VALUES(?,?,?,'ubl_xml',?,'application/xml',?,?,?)").bind(randomUUID(),T,id,`${T}/${id}/document.xml`,btoa(unescape(encodeURIComponent(ubl))),ublChecksum,new TextEncoder().encode(ubl).length),d.prepare("INSERT INTO electronic_document_files(id,tenant_id,document_id,file_type,storage_key,content_type,content_base64,checksum_sha256,size_bytes) VALUES(?,?,?,'graphic_html',?,'text/html',?,?,?)").bind(randomUUID(),T,id,`${T}/${id}/graphic.html`,btoa(unescape(encodeURIComponent(html))),htmlChecksum,new TextEncoder().encode(html).length),event(d,T,id,user,"created",null,status,{provider:provider.name,environment:provider.environment})];
  try{await d.batch(stmts)}catch(error){const existing=await d.prepare("SELECT id,number,status FROM electronic_documents WHERE tenant_id=? AND idempotency_key=?").bind(T,idempotency).first();if(existing)return Response.json({document:existing,duplicate:true});throw error}return Response.json({document:{id,number,status},queued:status==="queued"},{status:201});
}

export async function PATCH(req:Request){
  const access=await requireAccess(req,"settings","edit");if(access.error)return access.error;const p=await req.json() as {documentId?:string},d=getRuntimeEnv().DB,T=access.user.tenantId,user=access.user.id,document=await d.prepare("SELECT x.id,x.status,x.retry_count retryCount,x.number,x.lines_snapshot lines,x.customer_snapshot customer,x.issuer_snapshot issuer,x.subtotal_minor subtotalMinor,x.tax_minor taxMinor,x.total_minor totalMinor,x.currency,x.issue_date issueDate,x.document_type documentType,p.provider_type providerType,p.environment,p.endpoint,p.credential_reference credentialReference FROM electronic_documents x JOIN electronic_billing_providers p ON p.id=x.provider_id WHERE x.id=? AND x.tenant_id=? AND x.status='queued' AND (x.next_retry_at IS NULL OR x.next_retry_at<=CURRENT_TIMESTAMP)").bind(p.documentId,T).first<any>();if(!document)return Response.json({error:"No hay documento listo para transmitir"},{status:404});
  const attempt=document.retryCount+1,attemptId=randomUUID(),payload={number:document.number,profile:document.documentType==="equivalent"?"DIAN-DEE-1.0":"DIAN-FEV-1.9",environment:document.environment};await d.batch([d.prepare("UPDATE electronic_documents SET status='sending',updated_at=CURRENT_TIMESTAMP WHERE id=? AND status='queued'").bind(document.id),d.prepare("INSERT INTO electronic_document_attempts(id,tenant_id,document_id,attempt_number,request_payload,result) VALUES(?,?,?,?,?,'pending')").bind(attemptId,T,document.id,attempt,JSON.stringify(payload)),event(d,T,document.id,user,"transmission_started","queued","sending",{attempt})]);
  let accepted=false,temporary=false,code="",message="";if(document.providerType==="sandbox"){accepted=true;code="00";message="Aceptado en simulador de habilitación POS360"}else if(!document.endpoint||!document.credentialReference){temporary=true;code="PROVIDER_CONFIG";message="Proveedor sin endpoint o referencia segura de credencial"}else{temporary=true;code="ADAPTER_REQUIRED";message="Instale el adaptador certificado del proveedor tecnológico seleccionado"}
  const next=accepted?"accepted":temporary&&attempt<5?"queued":"rejected",cufe=accepted?await hash(`${document.number}|${document.totalMinor}|${document.issueDate}`):null,nextRetry=next==="queued"?new Date(Date.now()+Math.min(3600,30*2**attempt)*1000).toISOString():null,result=accepted?"accepted":temporary?"temporary_error":"rejected",response={code,message,accepted};await d.batch([d.prepare("UPDATE electronic_documents SET status=?,cufe=COALESCE(?,cufe),qr_data=COALESCE(?,qr_data),provider_status_code=?,provider_message=?,retry_count=?,next_retry_at=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(next,cufe,cufe?`https://catalogo-vpfe.dian.gov.co/document/searchqr?documentkey=${cufe}`:null,code,message,attempt,nextRetry,document.id),d.prepare("UPDATE electronic_document_attempts SET response_payload=?,http_status=?,result=?,error_code=?,error_message=?,completed_at=CURRENT_TIMESTAMP WHERE id=?").bind(JSON.stringify(response),accepted?200:503,result,accepted?null:code,accepted?null:message,attemptId),d.prepare("INSERT INTO electronic_document_files(id,tenant_id,document_id,file_type,storage_key,content_type,content_base64,checksum_sha256,size_bytes) VALUES(?,?,?,'provider_response',?,'application/json',?,?,?) ON CONFLICT(document_id,file_type) DO UPDATE SET content_base64=excluded.content_base64,checksum_sha256=excluded.checksum_sha256,size_bytes=excluded.size_bytes,created_at=CURRENT_TIMESTAMP").bind(randomUUID(),T,document.id,`${T}/${document.id}/provider-response.json`,btoa(JSON.stringify(response)),await hash(JSON.stringify(response)),JSON.stringify(response).length),event(d,T,document.id,user,"transmission_result","sending",next,response)]);return Response.json({document:{id:document.id,status:next,cufe,retryCount:attempt,nextRetryAt:nextRetry},response});
}
